{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/user.birthday.read": {
          "description": "View your complete date of birth"
        },
        "https://www.googleapis.com/auth/userinfo.profile": {
          "description": "See your personal info, including any personal info you've made publicly available"
        },
        "https://www.googleapis.com/auth/user.organization.read": {
          "description": "See your education, work history and org info"
        },
        "https://www.googleapis.com/auth/user.addresses.read": {
          "description": "View your street addresses"
        },
        "https://www.googleapis.com/auth/user.gender.read": {
          "description": "See your gender"
        },
        "https://www.googleapis.com/auth/user.phonenumbers.read": {
          "description": "View your phone numbers"
        },
        "https://www.googleapis.com/auth/contacts.readonly": {
          "description": "See and download your contacts"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        },
        "https://www.googleapis.com/auth/contacts": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/user.emails.read": {
          "description": "View your email addresses"
        },
        "https://www.googleapis.com/auth/directory.readonly": {
          "description": "See and download your organization's GSuite directory"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "name": "people",
  "version": "v1",
  "protocol": "rest",
  "servicePath": "",
  "baseUrl": "https://people.googleapis.com/",
  "title": "People API",
  "version_module": true,
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://people.mtls.googleapis.com/",
  "id": "people:v1",
  "documentationLink": "https://developers.google.com/people/",
  "rootUrl": "https://people.googleapis.com/",
  "revision": "20200615",
  "description": "Provides access to information about profiles and contacts.",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "canonicalName": "People Service",
  "resources": {
    "contactGroups": {
      "methods": {
        "create": {
          "description": "Create a new contact group owned by the authenticated user.",
          "httpMethod": "POST",
          "path": "v1/contactGroups",
          "id": "people.contactGroups.create",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "flatPath": "v1/contactGroups"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "id": "people.contactGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "description": "Get a specific contact group owned by the authenticated user by specifying\na contact group resource name.",
          "path": "v1/{+resourceName}"
        },
        "list": {
          "path": "v1/contactGroups",
          "id": "people.contactGroups.list",
          "description": "List all contact groups owned by the authenticated user. Members of the\ncontact groups are not populated.",
          "httpMethod": "GET",
          "flatPath": "v1/contactGroups",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "id": "people.contactGroups.update",
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "path": "v1/{+resourceName}",
          "httpMethod": "PUT",
          "description": "Update the name of an existing contact group owned by the authenticated\nuser."
        },
        "batchGet": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly"
          ],
          "httpMethod": "GET",
          "description": "Get a list of contact groups owned by the authenticated user by specifying\na list of contact group resource names.",
          "path": "v1/contactGroups:batchGet",
          "id": "people.contactGroups.batchGet",
          "flatPath": "v1/contactGroups:batchGet"
        },
        "delete": {
          "path": "v1/{+resourceName}",
          "httpMethod": "DELETE",
          "flatPath": "v1/contactGroups/{contactGroupsId}",
          "id": "people.contactGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "description": "Delete an existing contact group owned by the authenticated user by\nspecifying a contact group resource name."
        }
      },
      "resources": {
        "members": {
          "methods": {
            "modify": {
              "id": "people.contactGroups.members.modify",
              "description": "Modify the members of a contact group owned by the authenticated user.\n\nThe only system contact groups that can have members added are\n`contactGroups/myContacts` and `contactGroups/starred`. Other system\ncontact groups are deprecated and can only have contacts removed.",
              "httpMethod": "POST",
              "path": "v1/{+resourceName}/members:modify",
              "scopes": [
                "https://www.googleapis.com/auth/contacts"
              ],
              "flatPath": "v1/contactGroups/{contactGroupsId}/members:modify"
            }
          }
        }
      }
    },
    "otherContacts": {
      "methods": {
        "copyOtherContactToMyContactsGroup": {
          "httpMethod": "POST",
          "path": "v1/{+resourceName}:copyOtherContactToMyContactsGroup",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "description": "Copies an \"Other contact\" to a new contact in the user's \"myContacts\" group",
          "id": "people.otherContacts.copyOtherContactToMyContactsGroup",
          "flatPath": "v1/otherContacts/{otherContactsId}:copyOtherContactToMyContactsGroup"
        },
        "list": {
          "path": "v1/otherContacts",
          "httpMethod": "GET",
          "id": "people.otherContacts.list",
          "flatPath": "v1/otherContacts",
          "description": "List all \"Other contacts\", that is contacts that are not in a contact\ngroup. \"Other contacts\" are typically auto created contacts from\ninteractions."
        }
      }
    },
    "people": {
      "methods": {
        "updateContact": {
          "flatPath": "v1/people/{peopleId}:updateContact",
          "description": "Update contact data for an existing contact person. Any non-contact data\nwill not be modified.\n\nThe request throws a 400 error if `updatePersonFields` is not specified.\n\nThe request throws a 400 error if `person.metadata.sources` is not\nspecified for the contact to be updated.\n\nThe request throws a 400 error with an error with reason\n`\"failedPrecondition\"` if `person.metadata.sources.etag` is different than\nthe contact's etag, which indicates the contact has[...]",
          "path": "v1/{+resourceName}:updateContact",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "id": "people.people.updateContact"
        },
        "deleteContactPhoto": {
          "flatPath": "v1/people/{peopleId}:deleteContactPhoto",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "id": "people.people.deleteContactPhoto",
          "path": "v1/{+resourceName}:deleteContactPhoto",
          "description": "Delete a contact's photo."
        },
        "deleteContact": {
          "path": "v1/{+resourceName}:deleteContact",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "description": "Delete a contact person. Any non-contact data will not be deleted.",
          "flatPath": "v1/people/{peopleId}:deleteContact",
          "id": "people.people.deleteContact",
          "httpMethod": "DELETE"
        },
        "listDirectoryPeople": {
          "flatPath": "v1/people:listDirectoryPeople",
          "path": "v1/people:listDirectoryPeople",
          "id": "people.people.listDirectoryPeople",
          "scopes": [
            "https://www.googleapis.com/auth/directory.readonly"
          ],
          "description": "Provides a list of domain profiles and domain contacts in the authenticated\nuser's domain directory.",
          "httpMethod": "GET"
        },
        "get": {
          "path": "v1/{+resourceName}",
          "id": "people.people.get",
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.gender.read",
            "https://www.googleapis.com/auth/user.organization.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "httpMethod": "GET",
          "description": "Provides information about a person by specifying a resource name. Use\n`people/me` to indicate the authenticated user.\n\nThe request throws a 400 error if 'personFields' is not specified.",
          "flatPath": "v1/people/{peopleId}"
        },
        "updateContactPhoto": {
          "id": "people.people.updateContactPhoto",
          "description": "Update a contact's photo.",
          "httpMethod": "PATCH",
          "path": "v1/{+resourceName}:updateContactPhoto",
          "flatPath": "v1/people/{peopleId}:updateContactPhoto",
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ]
        },
        "searchDirectoryPeople": {
          "id": "people.people.searchDirectoryPeople",
          "httpMethod": "GET",
          "path": "v1/people:searchDirectoryPeople",
          "scopes": [
            "https://www.googleapis.com/auth/directory.readonly"
          ],
          "flatPath": "v1/people:searchDirectoryPeople",
          "description": "Provides a list of domain profiles and domain contacts in the authenticated\nuser's domain directory that match the search query."
        },
        "createContact": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts"
          ],
          "path": "v1/people:createContact",
          "flatPath": "v1/people:createContact",
          "id": "people.people.createContact",
          "description": "Create a new contact and return the person resource for that contact.",
          "httpMethod": "POST"
        },
        "getBatchGet": {
          "scopes": [
            "https://www.googleapis.com/auth/contacts",
            "https://www.googleapis.com/auth/contacts.readonly",
            "https://www.googleapis.com/auth/directory.readonly",
            "https://www.googleapis.com/auth/user.addresses.read",
            "https://www.googleapis.com/auth/user.birthday.read",
            "https://www.googleapis.com/auth/user.emails.read",
            "https://www.googleapis.com/auth/user.gender.read",
            "https://www.googleapis.com/auth/user.organization.read",
            "https://www.googleapis.com/auth/user.phonenumbers.read",
            "https://www.googleapis.com/auth/userinfo.email",
            "https://www.googleapis.com/auth/userinfo.profile"
          ],
          "path": "v1/people:batchGet",
          "flatPath": "v1/people:batchGet",
          "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.\n\nThe request throws a 400 error if 'personFields' is not specified.",
          "httpMethod": "GET",
          "id": "people.people.getBatchGet"
        }
      },
      "resources": {
        "connections": {
          "methods": {
            "list": {
              "description": "Provides a list of the authenticated user's contacts.\n\nThe request throws a 400 error if 'personFields' is not specified.",
              "flatPath": "v1/people/{peopleId}/connections",
              "id": "people.people.connections.list",
              "scopes": [
                "https://www.googleapis.com/auth/contacts",
                "https://www.googleapis.com/auth/contacts.readonly"
              ],
              "path": "v1/{+resourceName}/connections",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "ownerName": "Google",
  "basePath": ""
}
