/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.cloudchannel.v1.model;

/**
 * Defines price at resource tier level. For example, an offer with following definition : * Tier 1:
 * Provide 25% discount for all seats between 1 and 25. * Tier 2: Provide 10% discount for all seats
 * between 26 and 100. * Tier 3: Provide flat 15% discount for all seats above 100. Each of these
 * tiers is represented as a PriceTier.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Channel API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudChannelV1PriceTier extends com.google.api.client.json.GenericJson {

  /**
   * First resource for which the tier price applies.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer firstResource;

  /**
   * Last resource for which the tier price applies.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lastResource;

  /**
   * Price of the tier.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudChannelV1Price price;

  /**
   * First resource for which the tier price applies.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getFirstResource() {
    return firstResource;
  }

  /**
   * First resource for which the tier price applies.
   * @param firstResource firstResource or {@code null} for none
   */
  public GoogleCloudChannelV1PriceTier setFirstResource(java.lang.Integer firstResource) {
    this.firstResource = firstResource;
    return this;
  }

  /**
   * Last resource for which the tier price applies.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLastResource() {
    return lastResource;
  }

  /**
   * Last resource for which the tier price applies.
   * @param lastResource lastResource or {@code null} for none
   */
  public GoogleCloudChannelV1PriceTier setLastResource(java.lang.Integer lastResource) {
    this.lastResource = lastResource;
    return this;
  }

  /**
   * Price of the tier.
   * @return value or {@code null} for none
   */
  public GoogleCloudChannelV1Price getPrice() {
    return price;
  }

  /**
   * Price of the tier.
   * @param price price or {@code null} for none
   */
  public GoogleCloudChannelV1PriceTier setPrice(GoogleCloudChannelV1Price price) {
    this.price = price;
    return this;
  }

  @Override
  public GoogleCloudChannelV1PriceTier set(String fieldName, Object value) {
    return (GoogleCloudChannelV1PriceTier) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudChannelV1PriceTier clone() {
    return (GoogleCloudChannelV1PriceTier) super.clone();
  }

}
