/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.searchads360.v23.model;

/**
 * Represents a bidding seasonality adjustment. Cannot be used in manager accounts. See "About
 * seasonality adjustments" at https://support.google.com/google-ads/answer/10369906.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Search Ads 360 Reporting API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment extends com.google.api.client.json.GenericJson {

  /**
   * The seasonality adjustment will apply to all the campaigns under the listed channels
   * retroactively as well as going forward when the scope of this adjustment is CHANNEL. The
   * supported advertising channel types are DISPLAY, SEARCH and SHOPPING. Note: a seasonality
   * adjustment with both advertising_channel_types and campaign_ids is not supported.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> advertisingChannelTypes;

  /**
   * The seasonality adjustment will apply to the campaigns listed when the scope of this adjustment
   * is CAMPAIGN. The maximum number of campaigns per event is 2000. Note: a seasonality adjustment
   * with both advertising_channel_types and campaign_ids is not supported.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> campaigns;

  /**
   * Conversion rate modifier estimated based on expected conversion rate changes. When this field
   * is unset or set to 1.0 no adjustment will be applied to traffic. The allowed range is 0.1 to
   * 10.0.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double conversionRateModifier;

  /**
   * The description of the seasonality adjustment. The description can be at most 2048 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * If not specified, all devices will be included in this adjustment. Otherwise, only the
   * specified targeted devices will be included in this adjustment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> devices;

  /**
   * Required. The exclusive end time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * The length of [start_date_time, end_date_time) interval must be within (0, 14 days].
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String endDateTime;

  /**
   * The name of the seasonality adjustment. The name can be at most 255 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Immutable. The resource name of the seasonality adjustment. Seasonality adjustment resource
   * names have the form:
   * `customers/{customer_id}/biddingSeasonalityAdjustments/{seasonality_adjustment_id}`
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String resourceName;

  /**
   * The scope of the seasonality adjustment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String scope;

  /**
   * Output only. The ID of the seasonality adjustment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long seasonalityAdjustmentId;

  /**
   * Required. The inclusive start time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * A seasonality adjustment is forward looking and should be used for events that start and end in
   * the future.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String startDateTime;

  /**
   * Output only. The status of the seasonality adjustment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String status;

  /**
   * The seasonality adjustment will apply to all the campaigns under the listed channels
   * retroactively as well as going forward when the scope of this adjustment is CHANNEL. The
   * supported advertising channel types are DISPLAY, SEARCH and SHOPPING. Note: a seasonality
   * adjustment with both advertising_channel_types and campaign_ids is not supported.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getAdvertisingChannelTypes() {
    return advertisingChannelTypes;
  }

  /**
   * The seasonality adjustment will apply to all the campaigns under the listed channels
   * retroactively as well as going forward when the scope of this adjustment is CHANNEL. The
   * supported advertising channel types are DISPLAY, SEARCH and SHOPPING. Note: a seasonality
   * adjustment with both advertising_channel_types and campaign_ids is not supported.
   * @param advertisingChannelTypes advertisingChannelTypes or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setAdvertisingChannelTypes(java.util.List<java.lang.String> advertisingChannelTypes) {
    this.advertisingChannelTypes = advertisingChannelTypes;
    return this;
  }

  /**
   * The seasonality adjustment will apply to the campaigns listed when the scope of this adjustment
   * is CAMPAIGN. The maximum number of campaigns per event is 2000. Note: a seasonality adjustment
   * with both advertising_channel_types and campaign_ids is not supported.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getCampaigns() {
    return campaigns;
  }

  /**
   * The seasonality adjustment will apply to the campaigns listed when the scope of this adjustment
   * is CAMPAIGN. The maximum number of campaigns per event is 2000. Note: a seasonality adjustment
   * with both advertising_channel_types and campaign_ids is not supported.
   * @param campaigns campaigns or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setCampaigns(java.util.List<java.lang.String> campaigns) {
    this.campaigns = campaigns;
    return this;
  }

  /**
   * Conversion rate modifier estimated based on expected conversion rate changes. When this field
   * is unset or set to 1.0 no adjustment will be applied to traffic. The allowed range is 0.1 to
   * 10.0.
   * @return value or {@code null} for none
   */
  public java.lang.Double getConversionRateModifier() {
    return conversionRateModifier;
  }

  /**
   * Conversion rate modifier estimated based on expected conversion rate changes. When this field
   * is unset or set to 1.0 no adjustment will be applied to traffic. The allowed range is 0.1 to
   * 10.0.
   * @param conversionRateModifier conversionRateModifier or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setConversionRateModifier(java.lang.Double conversionRateModifier) {
    this.conversionRateModifier = conversionRateModifier;
    return this;
  }

  /**
   * The description of the seasonality adjustment. The description can be at most 2048 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * The description of the seasonality adjustment. The description can be at most 2048 characters.
   * @param description description or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * If not specified, all devices will be included in this adjustment. Otherwise, only the
   * specified targeted devices will be included in this adjustment.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getDevices() {
    return devices;
  }

  /**
   * If not specified, all devices will be included in this adjustment. Otherwise, only the
   * specified targeted devices will be included in this adjustment.
   * @param devices devices or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setDevices(java.util.List<java.lang.String> devices) {
    this.devices = devices;
    return this;
  }

  /**
   * Required. The exclusive end time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * The length of [start_date_time, end_date_time) interval must be within (0, 14 days].
   * @return value or {@code null} for none
   */
  public java.lang.String getEndDateTime() {
    return endDateTime;
  }

  /**
   * Required. The exclusive end time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * The length of [start_date_time, end_date_time) interval must be within (0, 14 days].
   * @param endDateTime endDateTime or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setEndDateTime(java.lang.String endDateTime) {
    this.endDateTime = endDateTime;
    return this;
  }

  /**
   * The name of the seasonality adjustment. The name can be at most 255 characters.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the seasonality adjustment. The name can be at most 255 characters.
   * @param name name or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Immutable. The resource name of the seasonality adjustment. Seasonality adjustment resource
   * names have the form:
   * `customers/{customer_id}/biddingSeasonalityAdjustments/{seasonality_adjustment_id}`
   * @return value or {@code null} for none
   */
  public java.lang.String getResourceName() {
    return resourceName;
  }

  /**
   * Immutable. The resource name of the seasonality adjustment. Seasonality adjustment resource
   * names have the form:
   * `customers/{customer_id}/biddingSeasonalityAdjustments/{seasonality_adjustment_id}`
   * @param resourceName resourceName or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setResourceName(java.lang.String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * The scope of the seasonality adjustment.
   * @return value or {@code null} for none
   */
  public java.lang.String getScope() {
    return scope;
  }

  /**
   * The scope of the seasonality adjustment.
   * @param scope scope or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setScope(java.lang.String scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Output only. The ID of the seasonality adjustment.
   * @return value or {@code null} for none
   */
  public java.lang.Long getSeasonalityAdjustmentId() {
    return seasonalityAdjustmentId;
  }

  /**
   * Output only. The ID of the seasonality adjustment.
   * @param seasonalityAdjustmentId seasonalityAdjustmentId or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setSeasonalityAdjustmentId(java.lang.Long seasonalityAdjustmentId) {
    this.seasonalityAdjustmentId = seasonalityAdjustmentId;
    return this;
  }

  /**
   * Required. The inclusive start time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * A seasonality adjustment is forward looking and should be used for events that start and end in
   * the future.
   * @return value or {@code null} for none
   */
  public java.lang.String getStartDateTime() {
    return startDateTime;
  }

  /**
   * Required. The inclusive start time of the seasonality adjustment in yyyy-MM-dd HH:mm:ss format.
   * A seasonality adjustment is forward looking and should be used for events that start and end in
   * the future.
   * @param startDateTime startDateTime or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setStartDateTime(java.lang.String startDateTime) {
    this.startDateTime = startDateTime;
    return this;
  }

  /**
   * Output only. The status of the seasonality adjustment.
   * @return value or {@code null} for none
   */
  public java.lang.String getStatus() {
    return status;
  }

  /**
   * Output only. The status of the seasonality adjustment.
   * @param status status or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment setStatus(java.lang.String status) {
    this.status = status;
    return this;
  }

  @Override
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment set(String fieldName, Object value) {
    return (GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment) super.set(fieldName, value);
  }

  @Override
  public GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment clone() {
    return (GoogleAdsSearchads360V23ResourcesBiddingSeasonalityAdjustment) super.clone();
  }

}
