/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.searchads360.v23.model;

/**
 * The biddability setting for the specified campaign only for all conversion actions with a
 * matching category and origin.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Search Ads 360 Reporting API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAdsSearchads360V23ResourcesCampaignConversionGoal extends com.google.api.client.json.GenericJson {

  /**
   * The biddability of the campaign conversion goal.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean biddable;

  /**
   * Immutable. The campaign with which this campaign conversion goal is associated.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String campaign;

  /**
   * The conversion category of this campaign conversion goal.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String category;

  /**
   * The conversion origin of this campaign conversion goal.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String origin;

  /**
   * Immutable. The resource name of the campaign conversion goal. Campaign conversion goal resource
   * names have the form:
   * `customers/{customer_id}/campaignConversionGoals/{campaign_id}~{category}~{origin}`
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String resourceName;

  /**
   * Search Ads 360 biddability of the campaign conversion goal.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean searchAds360Biddable;

  /**
   * The biddability of the campaign conversion goal.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getBiddable() {
    return biddable;
  }

  /**
   * The biddability of the campaign conversion goal.
   * @param biddable biddable or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setBiddable(java.lang.Boolean biddable) {
    this.biddable = biddable;
    return this;
  }

  /**
   * Immutable. The campaign with which this campaign conversion goal is associated.
   * @return value or {@code null} for none
   */
  public java.lang.String getCampaign() {
    return campaign;
  }

  /**
   * Immutable. The campaign with which this campaign conversion goal is associated.
   * @param campaign campaign or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setCampaign(java.lang.String campaign) {
    this.campaign = campaign;
    return this;
  }

  /**
   * The conversion category of this campaign conversion goal.
   * @return value or {@code null} for none
   */
  public java.lang.String getCategory() {
    return category;
  }

  /**
   * The conversion category of this campaign conversion goal.
   * @param category category or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setCategory(java.lang.String category) {
    this.category = category;
    return this;
  }

  /**
   * The conversion origin of this campaign conversion goal.
   * @return value or {@code null} for none
   */
  public java.lang.String getOrigin() {
    return origin;
  }

  /**
   * The conversion origin of this campaign conversion goal.
   * @param origin origin or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setOrigin(java.lang.String origin) {
    this.origin = origin;
    return this;
  }

  /**
   * Immutable. The resource name of the campaign conversion goal. Campaign conversion goal resource
   * names have the form:
   * `customers/{customer_id}/campaignConversionGoals/{campaign_id}~{category}~{origin}`
   * @return value or {@code null} for none
   */
  public java.lang.String getResourceName() {
    return resourceName;
  }

  /**
   * Immutable. The resource name of the campaign conversion goal. Campaign conversion goal resource
   * names have the form:
   * `customers/{customer_id}/campaignConversionGoals/{campaign_id}~{category}~{origin}`
   * @param resourceName resourceName or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setResourceName(java.lang.String resourceName) {
    this.resourceName = resourceName;
    return this;
  }

  /**
   * Search Ads 360 biddability of the campaign conversion goal.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getSearchAds360Biddable() {
    return searchAds360Biddable;
  }

  /**
   * Search Ads 360 biddability of the campaign conversion goal.
   * @param searchAds360Biddable searchAds360Biddable or {@code null} for none
   */
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal setSearchAds360Biddable(java.lang.Boolean searchAds360Biddable) {
    this.searchAds360Biddable = searchAds360Biddable;
    return this;
  }

  @Override
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal set(String fieldName, Object value) {
    return (GoogleAdsSearchads360V23ResourcesCampaignConversionGoal) super.set(fieldName, value);
  }

  @Override
  public GoogleAdsSearchads360V23ResourcesCampaignConversionGoal clone() {
    return (GoogleAdsSearchads360V23ResourcesCampaignConversionGoal) super.clone();
  }

}
