/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.searchads360.v23.model;

/**
 * Address for proximity criterion.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Search Ads 360 Reporting API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAdsSearchads360V23CommonAddressInfo extends com.google.api.client.json.GenericJson {

  /**
   * Name of the city.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cityName;

  /**
   * Country code.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String countryCode;

  /**
   * Postal code.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String postalCode;

  /**
   * Province or state code.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String provinceCode;

  /**
   * Province or state name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String provinceName;

  /**
   * Street address line 1.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String streetAddress;

  /**
   * Street address line 2. This field is write-only. It is only used for calculating the longitude
   * and latitude of an address when geo_point is empty.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String streetAddress2;

  /**
   * Name of the city.
   * @return value or {@code null} for none
   */
  public java.lang.String getCityName() {
    return cityName;
  }

  /**
   * Name of the city.
   * @param cityName cityName or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setCityName(java.lang.String cityName) {
    this.cityName = cityName;
    return this;
  }

  /**
   * Country code.
   * @return value or {@code null} for none
   */
  public java.lang.String getCountryCode() {
    return countryCode;
  }

  /**
   * Country code.
   * @param countryCode countryCode or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setCountryCode(java.lang.String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Postal code.
   * @return value or {@code null} for none
   */
  public java.lang.String getPostalCode() {
    return postalCode;
  }

  /**
   * Postal code.
   * @param postalCode postalCode or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setPostalCode(java.lang.String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Province or state code.
   * @return value or {@code null} for none
   */
  public java.lang.String getProvinceCode() {
    return provinceCode;
  }

  /**
   * Province or state code.
   * @param provinceCode provinceCode or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setProvinceCode(java.lang.String provinceCode) {
    this.provinceCode = provinceCode;
    return this;
  }

  /**
   * Province or state name.
   * @return value or {@code null} for none
   */
  public java.lang.String getProvinceName() {
    return provinceName;
  }

  /**
   * Province or state name.
   * @param provinceName provinceName or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setProvinceName(java.lang.String provinceName) {
    this.provinceName = provinceName;
    return this;
  }

  /**
   * Street address line 1.
   * @return value or {@code null} for none
   */
  public java.lang.String getStreetAddress() {
    return streetAddress;
  }

  /**
   * Street address line 1.
   * @param streetAddress streetAddress or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setStreetAddress(java.lang.String streetAddress) {
    this.streetAddress = streetAddress;
    return this;
  }

  /**
   * Street address line 2. This field is write-only. It is only used for calculating the longitude
   * and latitude of an address when geo_point is empty.
   * @return value or {@code null} for none
   */
  public java.lang.String getStreetAddress2() {
    return streetAddress2;
  }

  /**
   * Street address line 2. This field is write-only. It is only used for calculating the longitude
   * and latitude of an address when geo_point is empty.
   * @param streetAddress2 streetAddress2 or {@code null} for none
   */
  public GoogleAdsSearchads360V23CommonAddressInfo setStreetAddress2(java.lang.String streetAddress2) {
    this.streetAddress2 = streetAddress2;
    return this;
  }

  @Override
  public GoogleAdsSearchads360V23CommonAddressInfo set(String fieldName, Object value) {
    return (GoogleAdsSearchads360V23CommonAddressInfo) super.set(fieldName, value);
  }

  @Override
  public GoogleAdsSearchads360V23CommonAddressInfo clone() {
    return (GoogleAdsSearchads360V23CommonAddressInfo) super.clone();
  }

}
