/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.migrationcenter.v1.model;

/**
 * Guest installed application information.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Migration Center API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GuestInstalledApplication extends com.google.api.client.json.GenericJson {

  /**
   * Installed application name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String applicationName;

  /**
   * The time when the application was installed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String installTime;

  /**
   * License strings associated with the installed application.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> licenses;

  /**
   * Source path.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String path;

  /**
   * Installed application vendor.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String vendor;

  /**
   * Installed application version.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String version;

  /**
   * Installed application name.
   * @return value or {@code null} for none
   */
  public java.lang.String getApplicationName() {
    return applicationName;
  }

  /**
   * Installed application name.
   * @param applicationName applicationName or {@code null} for none
   */
  public GuestInstalledApplication setApplicationName(java.lang.String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

  /**
   * The time when the application was installed.
   * @return value or {@code null} for none
   */
  public String getInstallTime() {
    return installTime;
  }

  /**
   * The time when the application was installed.
   * @param installTime installTime or {@code null} for none
   */
  public GuestInstalledApplication setInstallTime(String installTime) {
    this.installTime = installTime;
    return this;
  }

  /**
   * License strings associated with the installed application.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getLicenses() {
    return licenses;
  }

  /**
   * License strings associated with the installed application.
   * @param licenses licenses or {@code null} for none
   */
  public GuestInstalledApplication setLicenses(java.util.List<java.lang.String> licenses) {
    this.licenses = licenses;
    return this;
  }

  /**
   * Source path.
   * @return value or {@code null} for none
   */
  public java.lang.String getPath() {
    return path;
  }

  /**
   * Source path.
   * @param path path or {@code null} for none
   */
  public GuestInstalledApplication setPath(java.lang.String path) {
    this.path = path;
    return this;
  }

  /**
   * Installed application vendor.
   * @return value or {@code null} for none
   */
  public java.lang.String getVendor() {
    return vendor;
  }

  /**
   * Installed application vendor.
   * @param vendor vendor or {@code null} for none
   */
  public GuestInstalledApplication setVendor(java.lang.String vendor) {
    this.vendor = vendor;
    return this;
  }

  /**
   * Installed application version.
   * @return value or {@code null} for none
   */
  public java.lang.String getVersion() {
    return version;
  }

  /**
   * Installed application version.
   * @param version version or {@code null} for none
   */
  public GuestInstalledApplication setVersion(java.lang.String version) {
    this.version = version;
    return this;
  }

  @Override
  public GuestInstalledApplication set(String fieldName, Object value) {
    return (GuestInstalledApplication) super.set(fieldName, value);
  }

  @Override
  public GuestInstalledApplication clone() {
    return (GuestInstalledApplication) super.clone();
  }

}
