{
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "version_module": true,
  "revision": "20210302",
  "ownerDomain": "google.com",
  "description": "API for provisioning and managing identity resources.",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        }
      }
    }
  },
  "servicePath": "",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Identity API",
  "kind": "discovery#restDescription",
  "name": "cloudidentity",
  "resources": {
    "devices": {
      "methods": {
        "list": {
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "description": "Lists/Searches devices.",
          "httpMethod": "GET",
          "id": "cloudidentity.devices.list"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1/devices/{devicesId}",
          "path": "v1/{+name}",
          "description": "Deletes the specified device.",
          "id": "cloudidentity.devices.delete"
        },
        "create": {
          "id": "cloudidentity.devices.create",
          "httpMethod": "POST",
          "path": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "flatPath": "v1/devices"
        },
        "wipe": {
          "description": "Wipes all data on the specified device.",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "id": "cloudidentity.devices.wipe",
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST"
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Retrieves the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.get",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists the client states for the given search query.",
                  "path": "v1/{+parent}/clientStates",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list"
                },
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                }
              }
            }
          },
          "methods": {
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser"
            },
            "lookup": {
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "httpMethod": "GET",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "path": "v1/{+parent}:lookup"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "httpMethod": "POST",
              "path": "v1/{+name}:approve",
              "description": "Approves device to access user data."
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1/{+name}"
            },
            "block": {
              "description": "Blocks device from accessing user data",
              "id": "cloudidentity.devices.deviceUsers.block",
              "path": "v1/{+name}:block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "httpMethod": "POST"
            },
            "wipe": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "path": "v1/{+name}:wipe",
              "httpMethod": "POST",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos."
            },
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "httpMethod": "POST",
              "path": "v1/{+name}:cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe"
            },
            "list": {
              "id": "cloudidentity.devices.deviceUsers.list",
              "httpMethod": "GET",
              "description": "Lists/Searches DeviceUsers.",
              "path": "v1/{+parent}/deviceUsers",
              "flatPath": "v1/devices/{devicesId}/deviceUsers"
            }
          }
        }
      }
    },
    "groups": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.patch",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "description": "Updates a `Group`."
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}"
        },
        "delete": {
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.delete",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`."
        },
        "list": {
          "description": "Lists the `Group`s under a customer or namespace.",
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/groups",
          "id": "cloudidentity.groups.list"
        },
        "lookup": {
          "flatPath": "v1/groups:lookup",
          "path": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "id": "cloudidentity.groups.lookup",
          "httpMethod": "GET"
        },
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "description": "Searches for `Group`s matching a specified query.",
          "flatPath": "v1/groups:search",
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "description": "Creates a Group.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "modifyMembershipRoles": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.get",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Retrieves a `Membership`."
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "path": "v1/{+parent}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`."
            },
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "description": "Creates a `Membership`.",
              "path": "v1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST"
            },
            "list": {
              "path": "v1/{+parent}/memberships",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists the `Membership`s within a `Group`.",
              "flatPath": "v1/groups/{groupsId}/memberships"
            },
            "searchTransitiveMemberships": {
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "httpMethod": "GET",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Deletes a `Membership`."
            },
            "searchTransitiveGroups": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups."
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "httpMethod": "GET",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph"
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "protocol": "rest",
  "documentationLink": "https://cloud.google.com/identity/",
  "canonicalName": "Cloud Identity",
  "batchPath": "batch",
  "ownerName": "Google",
  "id": "cloudidentity:v1",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "basePath": ""
}
