{
  "title": "Google Analytics Admin API",
  "id": "analyticsadmin:v1alpha",
  "revision": "20200924",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "version_module": true,
  "name": "analyticsadmin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "protocol": "rest",
  "version": "v1alpha",
  "discoveryVersion": "v1",
  "canonicalName": "Google Analytics Admin",
  "batchPath": "batch",
  "description": "",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        }
      }
    }
  },
  "servicePath": "",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "resources": {
    "accounts": {
      "resources": {
        "userLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks",
              "httpMethod": "POST",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "id": "analyticsadmin.accounts.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.accounts.userLinks.get"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchUpdate",
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "id": "analyticsadmin.accounts.userLinks.batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple users' links to an account or property."
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:audit",
              "id": "analyticsadmin.accounts.userLinks.audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs."
            },
            "list": {
              "id": "analyticsadmin.accounts.userLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks"
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchCreate",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.userLinks.batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created."
            },
            "batchDelete": {
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.userLinks.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST"
            },
            "patch": {
              "id": "analyticsadmin.accounts.userLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "description": "Updates a user link on an account or property.",
              "httpMethod": "PATCH"
            },
            "delete": {
              "id": "analyticsadmin.accounts.userLinks.delete",
              "description": "Deletes a user link on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            },
            "batchGet": {
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "id": "analyticsadmin.accounts.userLinks.batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/userLinks:batchGet"
            }
          }
        }
      },
      "methods": {
        "provisionAccountTicket": {
          "path": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "id": "analyticsadmin.accounts.provisionAccountTicket"
        },
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Updates an account.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch"
        },
        "getDataSharingSettings": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "path": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have App+Web properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "description": "Lookup for a single Account. Throws \"Target not found\" if no such account found, or if caller does not have permissions to access it."
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.accounts.delete"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accountSummaries.list",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1alpha/accountSummaries"
        }
      }
    },
    "properties": {
      "resources": {
        "webDataStreams": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.webDataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "description": "Lookup for a single WebDataStream Throws \"Target not found\" if no such web data stream found, or if the caller does not have permissions to access it.",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "analyticsadmin.properties.webDataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}",
              "description": "Updates a web stream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            },
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/globalSiteTag",
              "id": "analyticsadmin.properties.webDataStreams.getGlobalSiteTag",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams",
              "description": "Returns child web data streams under the specified parent property. Web data streams will be excluded if the caller does not have access. Returns an empty list if no relevant web data streams are found.",
              "id": "analyticsadmin.properties.webDataStreams.list",
              "path": "v1alpha/{+parent}/webDataStreams"
            },
            "create": {
              "path": "v1alpha/{+parent}/webDataStreams",
              "description": "Creates a web stream with the specified location and attributes.",
              "id": "analyticsadmin.properties.webDataStreams.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams"
            },
            "updateEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.webDataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "description": "Updates the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect."
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a web stream on a property.",
              "id": "analyticsadmin.properties.webDataStreams.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}"
            },
            "getEnhancedMeasurementSettings": {
              "description": "Returns the singleton enhanced measurement settings for this web stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.webDataStreams.getEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/webDataStreams/{webDataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "iosAppDataStreams": {
          "methods": {
            "get": {
              "description": "Lookup for a single IosAppDataStream Throws \"Target not found\" if no such iOS app data stream found, or if the caller does not have permissions to access it.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "id": "analyticsadmin.properties.iosAppDataStreams.get"
            },
            "patch": {
              "description": "Updates an iOS app stream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.iosAppDataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "description": "Returns child iOS app data streams under the specified parent property. iOS app data streams will be excluded if the caller does not have access. Returns an empty list if no relevant iOS app data streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "id": "analyticsadmin.properties.iosAppDataStreams.list"
            },
            "delete": {
              "description": "Deletes an iOS app stream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams/{iosAppDataStreamsId}",
              "id": "analyticsadmin.properties.iosAppDataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/iosAppDataStreams",
              "path": "v1alpha/{+parent}/iosAppDataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an iOS app data stream with the specified location and attributes.",
              "id": "analyticsadmin.properties.iosAppDataStreams.create"
            }
          }
        },
        "userLinks": {
          "methods": {
            "batchGet": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.userLinks.batchGet",
              "path": "v1alpha/{+parent}/userLinks:batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchGet",
              "description": "Gets information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchCreate": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/userLinks:batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple users' links to an account or property. This method is transactional. If any UserLink cannot be created, none of the UserLinks will be created.",
              "id": "analyticsadmin.properties.userLinks.batchCreate"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "description": "Gets information about a user's link to an account or property.",
              "id": "analyticsadmin.properties.userLinks.get"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/userLinks:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Updates information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchUpdate"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a user link on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "id": "analyticsadmin.properties.userLinks.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "audit": {
              "path": "v1alpha/{+parent}/userLinks:audit",
              "description": "Lists all user links on an account or property, including implicit ones that come from effective permissions granted by groups or organization admin roles. If a returned user link does not have direct permissions, they cannot be removed from the account or property directly with the DeleteUserLink command. They have to be removed from the group/etc that gives them permissions, which is currently only usable/discoverable in the GA or GMP UIs.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:audit",
              "id": "analyticsadmin.properties.userLinks.audit"
            },
            "list": {
              "path": "v1alpha/{+parent}/userLinks",
              "description": "Lists all user links on an account or property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "id": "analyticsadmin.properties.userLinks.list"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks",
              "description": "Creates a user link on an account or property. If the user with the specified email already has permissions on the account or property, then the user's existing permissions will be unioned with the permissions specified in the new UserLink.",
              "id": "analyticsadmin.properties.userLinks.create",
              "path": "v1alpha/{+parent}/userLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks/{userLinksId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.userLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes a user link on an account or property."
            },
            "batchDelete": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "id": "analyticsadmin.properties.userLinks.batchDelete",
              "path": "v1alpha/{+parent}/userLinks:batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/userLinks:batchDelete"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "description": "Updates a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "httpMethod": "GET"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "androidAppDataStreams": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "path": "v1alpha/{+parent}/androidAppDataStreams",
              "description": "Creates an android app stream with the specified location and attributes.",
              "id": "analyticsadmin.properties.androidAppDataStreams.create"
            },
            "delete": {
              "id": "analyticsadmin.properties.androidAppDataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes an android app stream on a property.",
              "httpMethod": "DELETE"
            },
            "list": {
              "id": "analyticsadmin.properties.androidAppDataStreams.list",
              "description": "Returns child android app streams under the specified parent property. Android app streams will be excluded if the caller does not have access. Returns an empty list if no relevant android app streams are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/androidAppDataStreams"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "description": "Lookup for a single AndroidAppDataStream Throws \"Target not found\" if no such android app data stream found, or if the caller does not have permissions to access it.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.androidAppDataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.androidAppDataStreams.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/androidAppDataStreams/{androidAppDataStreamsId}",
              "description": "Updates an android app stream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            },
            "list": {
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}"
            }
          }
        }
      },
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Only \"App+Web\" properties will be returned. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list"
        },
        "get": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single \"App+Web\" Property. Throws \"Target not found\" if no such property found, if property is not of the type \"App+Web\", or if caller does not have permissions to access it.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1alpha/properties",
          "description": "Creates an \"App+Web\" property with the specified location and attributes.",
          "path": "v1alpha/properties"
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "description": "Updates a property."
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, UserLinks) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found, or is not an A[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE"
        }
      }
    }
  },
  "ownerName": "Google",
  "basePath": "",
  "fullyEncodeReservedExpansion": true
}
