/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.aiplatform.v1beta1.model;

/**
 * Input for tool name match metric.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Vertex AI API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudAiplatformV1beta1ToolNameMatchInput extends com.google.api.client.json.GenericJson {

  /**
   * Required. Repeated tool name match instances.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleCloudAiplatformV1beta1ToolNameMatchInstance> instances;

  /**
   * Required. Spec for tool name match metric.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudAiplatformV1beta1ToolNameMatchSpec metricSpec;

  /**
   * Required. Repeated tool name match instances.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleCloudAiplatformV1beta1ToolNameMatchInstance> getInstances() {
    return instances;
  }

  /**
   * Required. Repeated tool name match instances.
   * @param instances instances or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1ToolNameMatchInput setInstances(java.util.List<GoogleCloudAiplatformV1beta1ToolNameMatchInstance> instances) {
    this.instances = instances;
    return this;
  }

  /**
   * Required. Spec for tool name match metric.
   * @return value or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1ToolNameMatchSpec getMetricSpec() {
    return metricSpec;
  }

  /**
   * Required. Spec for tool name match metric.
   * @param metricSpec metricSpec or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1ToolNameMatchInput setMetricSpec(GoogleCloudAiplatformV1beta1ToolNameMatchSpec metricSpec) {
    this.metricSpec = metricSpec;
    return this;
  }

  @Override
  public GoogleCloudAiplatformV1beta1ToolNameMatchInput set(String fieldName, Object value) {
    return (GoogleCloudAiplatformV1beta1ToolNameMatchInput) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudAiplatformV1beta1ToolNameMatchInput clone() {
    return (GoogleCloudAiplatformV1beta1ToolNameMatchInput) super.clone();
  }

}
