#!/bin/bash
# Install the local generator without dependencies first and then install the dependencies with hash checking.
#python2 -m pip install --no-deps -e ${GENERATOR_DIR} --user -q
#python2 -m pip install --require-hashes -r generator_requirements.txt --user

discoveries=($(find ~/Desktop/discovery-artifact-manager/discoveries -printf '%f\n' | cut -d '.' -f1,2 | sed 's/\n/ /'))


for discovery in "${discoveries[@]}"; do
  service=$(echo $discovery | cut -d '.' -f1)
  version=$(echo $discovery | cut -d '.' -f2)
  OUTPUT_DIR=$(realpath ../clients/google-api-services-$service/$version/2.0.0)
  DISCOVERY=$(realpath ~/Desktop/discovery-artifact-manager/discoveries/$discovery.json)
  echo $OUTPUT_DIR
  echo $DISCOVERY
  mkdir -p ${OUTPUT_DIR}
  python2 -m googleapis.codegen \
    --output_dir=${OUTPUT_DIR} \
    --input=${DISCOVERY} \
    --language=java \
    --language_variant=2.0.0 \
    --package_path=api/services
done

# run the local generator

