/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.analyticsadmin.v1alpha.model;

/**
 * A logical expression of Subproperty event filters.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Analytics Admin API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression extends com.google.api.client.json.GenericJson {

  /**
   * Creates a filter that matches a specific event. This cannot be set on the top level
   * SubpropertyEventFilterExpression.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleAnalyticsAdminV1alphaSubpropertyEventFilterCondition filterCondition;

  /**
   * A filter expression to be NOT'ed (inverted, complemented). It can only include a filter. This
   * cannot be set on the top level SubpropertyEventFilterExpression.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression notExpression;

  /**
   * A list of expressions to OR’ed together. Must only contain not_expression or filter_condition
   * expressions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpressionList orGroup;

  /**
   * Creates a filter that matches a specific event. This cannot be set on the top level
   * SubpropertyEventFilterExpression.
   * @return value or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterCondition getFilterCondition() {
    return filterCondition;
  }

  /**
   * Creates a filter that matches a specific event. This cannot be set on the top level
   * SubpropertyEventFilterExpression.
   * @param filterCondition filterCondition or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression setFilterCondition(GoogleAnalyticsAdminV1alphaSubpropertyEventFilterCondition filterCondition) {
    this.filterCondition = filterCondition;
    return this;
  }

  /**
   * A filter expression to be NOT'ed (inverted, complemented). It can only include a filter. This
   * cannot be set on the top level SubpropertyEventFilterExpression.
   * @return value or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression getNotExpression() {
    return notExpression;
  }

  /**
   * A filter expression to be NOT'ed (inverted, complemented). It can only include a filter. This
   * cannot be set on the top level SubpropertyEventFilterExpression.
   * @param notExpression notExpression or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression setNotExpression(GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression notExpression) {
    this.notExpression = notExpression;
    return this;
  }

  /**
   * A list of expressions to OR’ed together. Must only contain not_expression or filter_condition
   * expressions.
   * @return value or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpressionList getOrGroup() {
    return orGroup;
  }

  /**
   * A list of expressions to OR’ed together. Must only contain not_expression or filter_condition
   * expressions.
   * @param orGroup orGroup or {@code null} for none
   */
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression setOrGroup(GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpressionList orGroup) {
    this.orGroup = orGroup;
    return this;
  }

  @Override
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression set(String fieldName, Object value) {
    return (GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression) super.set(fieldName, value);
  }

  @Override
  public GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression clone() {
    return (GoogleAnalyticsAdminV1alphaSubpropertyEventFilterExpression) super.clone();
  }

}
