/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.looker.v1.model;

/**
 * Configuration for periodic export.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Looker (Google Cloud core) API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PeriodicExportConfig extends com.google.api.client.json.GenericJson {

  /**
   * Required. Cloud Storage bucket URI for periodic export. Format: gs://{bucket_name}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String gcsUri;

  /**
   * Required. Name of the CMEK key in KMS. Format:
   * projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kmsKey;

  /**
   * Required. Time in UTC to start the periodic export job.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private TimeOfDay startTime;

  /**
   * Required. Cloud Storage bucket URI for periodic export. Format: gs://{bucket_name}
   * @return value or {@code null} for none
   */
  public java.lang.String getGcsUri() {
    return gcsUri;
  }

  /**
   * Required. Cloud Storage bucket URI for periodic export. Format: gs://{bucket_name}
   * @param gcsUri gcsUri or {@code null} for none
   */
  public PeriodicExportConfig setGcsUri(java.lang.String gcsUri) {
    this.gcsUri = gcsUri;
    return this;
  }

  /**
   * Required. Name of the CMEK key in KMS. Format:
   * projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}
   * @return value or {@code null} for none
   */
  public java.lang.String getKmsKey() {
    return kmsKey;
  }

  /**
   * Required. Name of the CMEK key in KMS. Format:
   * projects/{project}/locations/{location}/keyRings/{key_ring}/cryptoKeys/{crypto_key}
   * @param kmsKey kmsKey or {@code null} for none
   */
  public PeriodicExportConfig setKmsKey(java.lang.String kmsKey) {
    this.kmsKey = kmsKey;
    return this;
  }

  /**
   * Required. Time in UTC to start the periodic export job.
   * @return value or {@code null} for none
   */
  public TimeOfDay getStartTime() {
    return startTime;
  }

  /**
   * Required. Time in UTC to start the periodic export job.
   * @param startTime startTime or {@code null} for none
   */
  public PeriodicExportConfig setStartTime(TimeOfDay startTime) {
    this.startTime = startTime;
    return this;
  }

  @Override
  public PeriodicExportConfig set(String fieldName, Object value) {
    return (PeriodicExportConfig) super.set(fieldName, value);
  }

  @Override
  public PeriodicExportConfig clone() {
    return (PeriodicExportConfig) super.clone();
  }

}
