/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.clouddeploy.v1.model;

/**
 * An analysis Job.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Deploy API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AnalysisJob extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Custom analysis checks from 3P metric providers that are run as part of the
   * analysis Job.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<CustomCheck> customChecks;

  /**
   * Output only. The amount of time in minutes the analysis Job will run, up to a maximum of 48
   * hours. If any check in this Job is still running when the duration ends, the Job keeps running
   * until that check completes.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String duration;

  /**
   * Output only. Google Cloud - based analysis checks that are run as part of the analysis Job.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudAnalysis googleCloud;

  /**
   * Output only. Custom analysis checks from 3P metric providers that are run as part of the
   * analysis Job.
   * @return value or {@code null} for none
   */
  public java.util.List<CustomCheck> getCustomChecks() {
    return customChecks;
  }

  /**
   * Output only. Custom analysis checks from 3P metric providers that are run as part of the
   * analysis Job.
   * @param customChecks customChecks or {@code null} for none
   */
  public AnalysisJob setCustomChecks(java.util.List<CustomCheck> customChecks) {
    this.customChecks = customChecks;
    return this;
  }

  /**
   * Output only. The amount of time in minutes the analysis Job will run, up to a maximum of 48
   * hours. If any check in this Job is still running when the duration ends, the Job keeps running
   * until that check completes.
   * @return value or {@code null} for none
   */
  public String getDuration() {
    return duration;
  }

  /**
   * Output only. The amount of time in minutes the analysis Job will run, up to a maximum of 48
   * hours. If any check in this Job is still running when the duration ends, the Job keeps running
   * until that check completes.
   * @param duration duration or {@code null} for none
   */
  public AnalysisJob setDuration(String duration) {
    this.duration = duration;
    return this;
  }

  /**
   * Output only. Google Cloud - based analysis checks that are run as part of the analysis Job.
   * @return value or {@code null} for none
   */
  public GoogleCloudAnalysis getGoogleCloud() {
    return googleCloud;
  }

  /**
   * Output only. Google Cloud - based analysis checks that are run as part of the analysis Job.
   * @param googleCloud googleCloud or {@code null} for none
   */
  public AnalysisJob setGoogleCloud(GoogleCloudAnalysis googleCloud) {
    this.googleCloud = googleCloud;
    return this;
  }

  @Override
  public AnalysisJob set(String fieldName, Object value) {
    return (AnalysisJob) super.set(fieldName, value);
  }

  @Override
  public AnalysisJob clone() {
    return (AnalysisJob) super.clone();
  }

}
