{
  "baseUrl": "https://area120tables.googleapis.com/",
  "documentationLink": "https://support.google.com/area120-tables/answer/10011390",
  "id": "area120tables:v1alpha1",
  "title": "Area120 Tables API",
  "version": "v1alpha1",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "discoveryVersion": "v1",
  "name": "area120tables",
  "protocol": "rest",
  "mtlsRootUrl": "https://area120tables.mtls.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://area120tables.googleapis.com/",
  "canonicalName": "Area120 Tables",
  "ownerName": "Google",
  "resources": {
    "workspaces": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists workspaces for the user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/tables"
          ],
          "flatPath": "v1alpha1/workspaces",
          "id": "area120tables.workspaces.list",
          "path": "v1alpha1/workspaces"
        },
        "get": {
          "flatPath": "v1alpha1/workspaces/{workspacesId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/tables"
          ],
          "description": "Gets a workspace. Returns NOT_FOUND if the workspace does not exist.",
          "httpMethod": "GET",
          "path": "v1alpha1/{+name}",
          "id": "area120tables.workspaces.get"
        }
      }
    },
    "tables": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/tables"
          ],
          "path": "v1alpha1/tables",
          "id": "area120tables.tables.list",
          "flatPath": "v1alpha1/tables",
          "httpMethod": "GET",
          "description": "Lists tables for the user."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly",
            "https://www.googleapis.com/auth/tables"
          ],
          "description": "Gets a table. Returns NOT_FOUND if the table does not exist.",
          "httpMethod": "GET",
          "path": "v1alpha1/{+name}",
          "flatPath": "v1alpha1/tables/{tablesId}",
          "id": "area120tables.tables.get"
        }
      },
      "resources": {
        "rows": {
          "methods": {
            "batchUpdate": {
              "flatPath": "v1alpha1/tables/{tablesId}/rows:batchUpdate",
              "path": "v1alpha1/{+parent}/rows:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ],
              "id": "area120tables.tables.rows.batchUpdate",
              "description": "Updates multiple rows.",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly",
                "https://www.googleapis.com/auth/tables"
              ],
              "flatPath": "v1alpha1/tables/{tablesId}/rows/{rowsId}",
              "path": "v1alpha1/{+name}",
              "id": "area120tables.tables.rows.get",
              "description": "Gets a row. Returns NOT_FOUND if the row does not exist in the table."
            },
            "delete": {
              "id": "area120tables.tables.rows.delete",
              "description": "Deletes a row.",
              "path": "v1alpha1/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha1/tables/{tablesId}/rows/{rowsId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ]
            },
            "batchCreate": {
              "description": "Creates multiple rows.",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ],
              "path": "v1alpha1/{+parent}/rows:batchCreate",
              "id": "area120tables.tables.rows.batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha1/tables/{tablesId}/rows:batchCreate"
            },
            "list": {
              "path": "v1alpha1/{+parent}/rows",
              "id": "area120tables.tables.rows.list",
              "description": "Lists rows in a table. Returns NOT_FOUND if the table does not exist.",
              "flatPath": "v1alpha1/tables/{tablesId}/rows",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly",
                "https://www.googleapis.com/auth/tables"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1alpha1/{+parent}/rows",
              "description": "Creates a row.",
              "flatPath": "v1alpha1/tables/{tablesId}/rows",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ],
              "id": "area120tables.tables.rows.create",
              "httpMethod": "POST"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "flatPath": "v1alpha1/tables/{tablesId}/rows:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ],
              "id": "area120tables.tables.rows.batchDelete",
              "description": "Deletes multiple rows.",
              "path": "v1alpha1/{+parent}/rows:batchDelete"
            },
            "patch": {
              "path": "v1alpha1/{+name}",
              "description": "Updates a row.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/tables"
              ],
              "id": "area120tables.tables.rows.patch",
              "flatPath": "v1alpha1/tables/{tablesId}/rows/{rowsId}"
            }
          }
        }
      }
    }
  },
  "description": "",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/tables": {
          "description": "See, edit, create, and delete your tables in Tables by Area 120"
        }
      }
    }
  },
  "revision": "20210319",
  "batchPath": "batch"
}
