/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.developerconnect.v1.model;

/**
 * The DeploymentEvent resource represents the deployment of the artifact within the InsightsConfig
 * resource.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Developer Connect API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DeploymentEvent extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The artifact deployments of the DeploymentEvent. Each artifact deployment contains
   * the artifact uri and the runtime configuration uri. For GKE, this would be all the containers
   * images that are deployed in the pod.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ArtifactDeployment> artifactDeployments;

  static {
    // hack to force ProGuard to consider ArtifactDeployment used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(ArtifactDeployment.class);
  }

  /**
   * Output only. The create time of the DeploymentEvent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String createTime;

  /**
   * Output only. The time at which the DeploymentEvent was deployed. This would be the min of all
   * ArtifactDeployment deploy_times.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String deployTime;

  /**
   * Identifier. The name of the DeploymentEvent. This name is provided by Developer Connect
   * insights. Format: projects/{project}/locations/{location}/insightsConfigs/{insights_config}/dep
   * loymentEvents/{uuid}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Output only. The runtime configurations where the DeploymentEvent happened.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RuntimeConfig runtimeConfig;

  /**
   * Output only. The runtime assigned URI of the DeploymentEvent. For GKE, this is the fully
   * qualified replica set uri. e.g. container.googleapis.com/projects/{project}/locations/{location
   * }/clusters/{cluster}/k8s/namespaces/{namespace}/apps/replicasets/{replica-set-id} For Cloud
   * Run, this is the revision name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String runtimeDeploymentUri;

  /**
   * Output only. The state of the DeploymentEvent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * Output only. The time at which the DeploymentEvent was undeployed, all artifacts are considered
   * undeployed once this time is set. This would be the max of all ArtifactDeployment
   * undeploy_times. If any ArtifactDeployment is still active (i.e. does not have an
   * undeploy_time), this field will be empty.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String undeployTime;

  /**
   * Output only. The update time of the DeploymentEvent.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String updateTime;

  /**
   * Output only. The artifact deployments of the DeploymentEvent. Each artifact deployment contains
   * the artifact uri and the runtime configuration uri. For GKE, this would be all the containers
   * images that are deployed in the pod.
   * @return value or {@code null} for none
   */
  public java.util.List<ArtifactDeployment> getArtifactDeployments() {
    return artifactDeployments;
  }

  /**
   * Output only. The artifact deployments of the DeploymentEvent. Each artifact deployment contains
   * the artifact uri and the runtime configuration uri. For GKE, this would be all the containers
   * images that are deployed in the pod.
   * @param artifactDeployments artifactDeployments or {@code null} for none
   */
  public DeploymentEvent setArtifactDeployments(java.util.List<ArtifactDeployment> artifactDeployments) {
    this.artifactDeployments = artifactDeployments;
    return this;
  }

  /**
   * Output only. The create time of the DeploymentEvent.
   * @return value or {@code null} for none
   */
  public String getCreateTime() {
    return createTime;
  }

  /**
   * Output only. The create time of the DeploymentEvent.
   * @param createTime createTime or {@code null} for none
   */
  public DeploymentEvent setCreateTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Output only. The time at which the DeploymentEvent was deployed. This would be the min of all
   * ArtifactDeployment deploy_times.
   * @return value or {@code null} for none
   */
  public String getDeployTime() {
    return deployTime;
  }

  /**
   * Output only. The time at which the DeploymentEvent was deployed. This would be the min of all
   * ArtifactDeployment deploy_times.
   * @param deployTime deployTime or {@code null} for none
   */
  public DeploymentEvent setDeployTime(String deployTime) {
    this.deployTime = deployTime;
    return this;
  }

  /**
   * Identifier. The name of the DeploymentEvent. This name is provided by Developer Connect
   * insights. Format: projects/{project}/locations/{location}/insightsConfigs/{insights_config}/dep
   * loymentEvents/{uuid}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. The name of the DeploymentEvent. This name is provided by Developer Connect
   * insights. Format: projects/{project}/locations/{location}/insightsConfigs/{insights_config}/dep
   * loymentEvents/{uuid}
   * @param name name or {@code null} for none
   */
  public DeploymentEvent setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Output only. The runtime configurations where the DeploymentEvent happened.
   * @return value or {@code null} for none
   */
  public RuntimeConfig getRuntimeConfig() {
    return runtimeConfig;
  }

  /**
   * Output only. The runtime configurations where the DeploymentEvent happened.
   * @param runtimeConfig runtimeConfig or {@code null} for none
   */
  public DeploymentEvent setRuntimeConfig(RuntimeConfig runtimeConfig) {
    this.runtimeConfig = runtimeConfig;
    return this;
  }

  /**
   * Output only. The runtime assigned URI of the DeploymentEvent. For GKE, this is the fully
   * qualified replica set uri. e.g. container.googleapis.com/projects/{project}/locations/{location
   * }/clusters/{cluster}/k8s/namespaces/{namespace}/apps/replicasets/{replica-set-id} For Cloud
   * Run, this is the revision name.
   * @return value or {@code null} for none
   */
  public java.lang.String getRuntimeDeploymentUri() {
    return runtimeDeploymentUri;
  }

  /**
   * Output only. The runtime assigned URI of the DeploymentEvent. For GKE, this is the fully
   * qualified replica set uri. e.g. container.googleapis.com/projects/{project}/locations/{location
   * }/clusters/{cluster}/k8s/namespaces/{namespace}/apps/replicasets/{replica-set-id} For Cloud
   * Run, this is the revision name.
   * @param runtimeDeploymentUri runtimeDeploymentUri or {@code null} for none
   */
  public DeploymentEvent setRuntimeDeploymentUri(java.lang.String runtimeDeploymentUri) {
    this.runtimeDeploymentUri = runtimeDeploymentUri;
    return this;
  }

  /**
   * Output only. The state of the DeploymentEvent.
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * Output only. The state of the DeploymentEvent.
   * @param state state or {@code null} for none
   */
  public DeploymentEvent setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * Output only. The time at which the DeploymentEvent was undeployed, all artifacts are considered
   * undeployed once this time is set. This would be the max of all ArtifactDeployment
   * undeploy_times. If any ArtifactDeployment is still active (i.e. does not have an
   * undeploy_time), this field will be empty.
   * @return value or {@code null} for none
   */
  public String getUndeployTime() {
    return undeployTime;
  }

  /**
   * Output only. The time at which the DeploymentEvent was undeployed, all artifacts are considered
   * undeployed once this time is set. This would be the max of all ArtifactDeployment
   * undeploy_times. If any ArtifactDeployment is still active (i.e. does not have an
   * undeploy_time), this field will be empty.
   * @param undeployTime undeployTime or {@code null} for none
   */
  public DeploymentEvent setUndeployTime(String undeployTime) {
    this.undeployTime = undeployTime;
    return this;
  }

  /**
   * Output only. The update time of the DeploymentEvent.
   * @return value or {@code null} for none
   */
  public String getUpdateTime() {
    return updateTime;
  }

  /**
   * Output only. The update time of the DeploymentEvent.
   * @param updateTime updateTime or {@code null} for none
   */
  public DeploymentEvent setUpdateTime(String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  @Override
  public DeploymentEvent set(String fieldName, Object value) {
    return (DeploymentEvent) super.set(fieldName, value);
  }

  @Override
  public DeploymentEvent clone() {
    return (DeploymentEvent) super.clone();
  }

}
