{
  "documentationLink": "https://developers.google.com/slides/",
  "basePath": "",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "View your Google Spreadsheets"
        },
        "https://www.googleapis.com/auth/presentations.readonly": {
          "description": "View your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/presentations": {
          "description": "View and manage your Google Slides presentations"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "version_module": true,
  "protocol": "rest",
  "description": "Reads and writes Google Slides presentations.",
  "title": "Google Slides API",
  "canonicalName": "Slides",
  "revision": "20200803",
  "servicePath": "",
  "rootUrl": "https://slides.googleapis.com/",
  "mtlsRootUrl": "https://slides.mtls.googleapis.com/",
  "baseUrl": "https://slides.googleapis.com/",
  "resources": {
    "presentations": {
      "methods": {
        "create": {
          "path": "v1/presentations",
          "flatPath": "v1/presentations",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/presentations"
          ],
          "description": "Creates a blank presentation using the title given in the request. If a `presentationId` is provided, it is used as the ID of the new presentation. Otherwise, a new ID is generated. Other fields in the request, including any provided content, are ignored. Returns the created presentation.",
          "id": "slides.presentations.create"
        },
        "batchUpdate": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "flatPath": "v1/presentations/{presentationId}:batchUpdate",
          "path": "v1/presentations/{presentationId}:batchUpdate",
          "httpMethod": "POST",
          "description": "Applies one or more updates to the presentation. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and o[...]",
          "id": "slides.presentations.batchUpdate"
        },
        "get": {
          "id": "slides.presentations.get",
          "httpMethod": "GET",
          "flatPath": "v1/presentations/{presentationsId}",
          "description": "Gets the latest version of the specified presentation.",
          "path": "v1/presentations/{+presentationId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/presentations",
            "https://www.googleapis.com/auth/presentations.readonly"
          ]
        }
      },
      "resources": {
        "pages": {
          "methods": {
            "get": {
              "id": "slides.presentations.pages.get",
              "httpMethod": "GET",
              "description": "Gets the latest version of the specified page in the presentation.",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ]
            },
            "getThumbnail": {
              "description": "Generates a thumbnail of the latest version of the specified page in the presentation and returns a URL to the thumbnail image. This request counts as an [expensive read request](/slides/limits) for quota purposes.",
              "flatPath": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "id": "slides.presentations.pages.getThumbnail",
              "path": "v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/presentations",
                "https://www.googleapis.com/auth/presentations.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "batchPath": "batch",
  "name": "slides",
  "version": "v1",
  "id": "slides:v1",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription"
}
