{
  "description": "Accesses report data in Google Analytics.",
  "revision": "20201016",
  "discoveryVersion": "v1",
  "servicePath": "",
  "name": "analyticsdata",
  "version": "v1alpha",
  "ownerName": "Google",
  "batchPath": "batch",
  "rootUrl": "https://analyticsdata.googleapis.com/",
  "resources": {
    "v1alpha": {
      "methods": {
        "batchRunPivotReports": {
          "flatPath": "v1alpha:batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsdata.batchRunPivotReports",
          "httpMethod": "POST",
          "path": "v1alpha:batchRunPivotReports",
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same Entity."
        },
        "runPivotReport": {
          "path": "v1alpha:runPivotReport",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "id": "analyticsdata.runPivotReport",
          "flatPath": "v1alpha:runPivotReport"
        },
        "batchRunReports": {
          "flatPath": "v1alpha:batchRunReports",
          "id": "analyticsdata.batchRunReports",
          "description": "Returns multiple reports in a batch. All reports must be for the same Entity.",
          "path": "v1alpha:batchRunReports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getUniversalMetadata": {
          "flatPath": "v1alpha/universalMetadata",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1alpha/universalMetadata",
          "id": "analyticsdata.getUniversalMetadata",
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. Dimensions and metrics will be mostly added over time, but renames and deletions may occur. This method returns Universal Metadata. Universal Metadata are dimensions and metrics applicable to any property such as `country` and `totalUsers`."
        },
        "runReport": {
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha:runReport",
          "id": "analyticsdata.runReport",
          "httpMethod": "POST",
          "path": "v1alpha:runReport"
        }
      }
    },
    "properties": {
      "methods": {
        "getMetadata": {
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics GA4 Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Univer[...]",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/metadata",
          "id": "analyticsdata.properties.getMetadata",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    }
  },
  "title": "Google Analytics Data API",
  "version_module": true,
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        }
      }
    }
  },
  "id": "analyticsdata:v1alpha",
  "kind": "discovery#restDescription",
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "canonicalName": "AnalyticsData",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/analytics/trusted-testing/analytics-data/"
}
