{
  "version_module": true,
  "resources": {
    "v1alpha": {
      "methods": {
        "runPivotReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha:runPivotReport",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data.",
          "id": "analyticsdata.runPivotReport",
          "flatPath": "v1alpha:runPivotReport",
          "httpMethod": "POST"
        },
        "runReport": {
          "id": "analyticsdata.runReport",
          "path": "v1alpha:runReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha:runReport"
        },
        "batchRunPivotReports": {
          "id": "analyticsdata.batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same Entity.",
          "path": "v1alpha:batchRunPivotReports",
          "flatPath": "v1alpha:batchRunPivotReports",
          "httpMethod": "POST"
        },
        "batchRunReports": {
          "path": "v1alpha:batchRunReports",
          "flatPath": "v1alpha:batchRunReports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns multiple reports in a batch. All reports must be for the same Entity.",
          "id": "analyticsdata.batchRunReports"
        },
        "getUniversalMetadata": {
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. Dimensions and metrics will be mostly added over time, but renames and deletions may occur. This method returns Universal Metadata. Universal Metadata are dimensions and metrics applicable to any property such as `country` and `totalUsers`.",
          "path": "v1alpha/universalMetadata",
          "httpMethod": "GET",
          "id": "analyticsdata.getUniversalMetadata",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/universalMetadata"
        }
      }
    }
  },
  "title": "Google Analytics Data API",
  "id": "analyticsdata:v1alpha",
  "documentationLink": "https://developers.google.com/analytics/trusted-testing/analytics-data/",
  "name": "analyticsdata",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        }
      }
    }
  },
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "canonicalName": "AnalyticsData",
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "description": "Accesses report data in Google Analytics.",
  "basePath": "",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "version": "v1alpha",
  "revision": "20200907",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://analyticsdata.googleapis.com/",
  "ownerName": "Google"
}
