/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Status data for storage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementV1StorageStatusReport extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Reports on disk
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementV1DiskInfo> disk;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementV1DiskInfo used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementV1DiskInfo.class);
  }

  /**
   * Output only. Timestamp of when the sample was collected on device
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String reportTime;

  /**
   * Output only. Reports on disk
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementV1DiskInfo> getDisk() {
    return disk;
  }

  /**
   * Output only. Reports on disk
   * @param disk disk or {@code null} for none
   */
  public GoogleChromeManagementV1StorageStatusReport setDisk(java.util.List<GoogleChromeManagementV1DiskInfo> disk) {
    this.disk = disk;
    return this;
  }

  /**
   * Output only. Timestamp of when the sample was collected on device
   * @return value or {@code null} for none
   */
  public String getReportTime() {
    return reportTime;
  }

  /**
   * Output only. Timestamp of when the sample was collected on device
   * @param reportTime reportTime or {@code null} for none
   */
  public GoogleChromeManagementV1StorageStatusReport setReportTime(String reportTime) {
    this.reportTime = reportTime;
    return this;
  }

  @Override
  public GoogleChromeManagementV1StorageStatusReport set(String fieldName, Object value) {
    return (GoogleChromeManagementV1StorageStatusReport) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementV1StorageStatusReport clone() {
    return (GoogleChromeManagementV1StorageStatusReport) super.clone();
  }

}
