{
  "version": "v1",
  "baseUrl": "https://www.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like\n    threads, messages, and labels.",
  "servicePath": "",
  "basePath": "",
  "id": "gmail:v1",
  "documentationLink": "https://developers.google.com/gmail/api/",
  "revision": "20200406",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "canonicalName": "Gmail",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "Manage your basic mail settings"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Insert mail into your mailbox"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "Manage mailbox labels"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "View and modify but not delete your email"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        }
      }
    }
  },
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "gmail",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "batchPath": "batch",
  "title": "Gmail API",
  "ownerName": "Google",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "description": "Gets the current user's Gmail profile.",
          "httpMethod": "GET",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "flatPath": "gmail/v1/users/{userId}/profile",
          "id": "gmail.users.getProfile",
          "path": "gmail/v1/users/{userId}/profile"
        },
        "watch": {
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "flatPath": "gmail/v1/users/{userId}/watch",
          "path": "gmail/v1/users/{userId}/watch",
          "id": "gmail.users.watch",
          "description": "Set up or update a push notification watch on the given user mailbox."
        },
        "stop": {
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "flatPath": "gmail/v1/users/{userId}/stop",
          "id": "gmail.users.stop",
          "path": "gmail/v1/users/{userId}/stop",
          "description": "Stop receiving push notifications for the given user mailbox."
        }
      },
      "resources": {
        "threads": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.delete",
              "description": "Immediately and permanently deletes the specified thread. This operation\ncannot be undone. Prefer \u003ccode\u003ethreads.trash\u003c/code\u003e instead."
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "id": "gmail.users.threads.trash",
              "description": "Moves the specified thread to the trash.",
              "httpMethod": "POST"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads",
              "path": "gmail/v1/users/{userId}/threads",
              "id": "gmail.users.threads.list",
              "description": "Lists the threads in the user's mailbox."
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages\nin the thread.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.get",
              "description": "Gets the specified thread."
            },
            "untrash": {
              "description": "Removes the specified thread from the trash.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "id": "gmail.users.threads.untrash"
            }
          }
        },
        "settings": {
          "methods": {
            "getLanguage": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.getLanguage",
              "path": "gmail/v1/users/{userId}/settings/language",
              "description": "Gets language settings."
            },
            "updatePop": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.updatePop",
              "description": "Updates POP settings."
            },
            "getPop": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.getPop",
              "description": "Gets POP settings."
            },
            "updateImap": {
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "description": "Updates IMAP settings.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateVacation": {
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.updateVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getImap": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.getImap",
              "description": "Gets IMAP settings."
            },
            "updateAutoForwarding": {
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.updateAutoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account.  A verified\nforwarding address must be specified when auto-forwarding is enabled.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "getVacation": {
              "description": "Gets vacation responder settings.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.getVacation"
            },
            "updateLanguage": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.updateLanguage",
              "description": "Updates language settings.\n\nIf successful, the return object contains the \u003ccode\u003edisplayLanguage\u003c/code\u003e\nthat was saved for the user, which may differ from the value passed into\nthe request. This is because the requested \u003ccode\u003edisplayLanguage\u003c/code\u003e may\nnot be directly supported by Gmail but have a close variant that is, and so\nthe variant may be chosen and saved instead."
            },
            "getAutoForwarding": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "description": "Gets the auto-forwarding setting for the specified account."
            }
          },
          "resources": {
            "sendAs": {
              "methods": {
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "description": "Deletes the specified send-as alias.  Revokes any verification that may\nhave been required for using it.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.list",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Lists the send-as aliases for the specified account.  The result includes\nthe primary send-as address associated with the account as well as any\ncustom \"from\" aliases.",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.create",
                  "description": "Creates a custom \"from\" send-as alias.  If an SMTP MSA is specified, Gmail\nwill attempt to connect to the SMTP service to validate the configuration\nbefore creating the alias.  If ownership verification is required for the\nalias, a message will be sent to the email address and the resource's\nverification status will be set to \u003ccode\u003epending\u003c/code\u003e; otherwise, the\nresource will be created with verification status set to\n\u003ccode\u003e[...]"
                },
                "verify": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "id": "gmail.users.settings.sendAs.verify",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "description": "Sends a verification email to the specified send-as alias address.\nThe verification status must be \u003ccode\u003epending\u003c/code\u003e.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority."
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.patch",
                  "description": "Patch the specified send-as alias."
                },
                "get": {
                  "description": "Gets the specified send-as alias.  Fails with an HTTP 404 error if the\nspecified address is not a member of the collection.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.get",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "update": {
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.update",
                  "description": "Updates a send-as alias.  If a signature is provided, Gmail will sanitize\nthe HTML before saving it with the alias.\n\nAddresses other than the primary address for the account can only be\nupdated by service account clients that have been delegated domain-wide\nauthority."
                }
              },
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "list": {
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    },
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic"
                      ]
                    },
                    "setDefault": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias."
                    },
                    "insert": {
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias.\nNote that pkcs12 format is required for the key.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    }
                  }
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "delete": {
                  "description": "Deletes the specified forwarding address and revokes any verification that\nmay have been required.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                },
                "list": {
                  "description": "Lists the forwarding addresses for the specified account.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.list"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "description": "Gets the specified forwarding address."
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Creates a forwarding address.  If ownership verification is required, a\nmessage will be sent to the recipient and the resource's verification\nstatus will be set to \u003ccode\u003epending\u003c/code\u003e; otherwise, the resource will be\ncreated with verification status set to \u003ccode\u003eaccepted\u003c/code\u003e.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority."
                }
              }
            },
            "filters": {
              "methods": {
                "delete": {
                  "description": "Deletes a filter.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.delete"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.list",
                  "description": "Lists the message filters of a Gmail user."
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.get",
                  "description": "Gets a filter."
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.create",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter."
                }
              }
            },
            "delegates": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.delete",
                  "description": "Removes the specified delegate (which can be of any verification status),\nand revokes any verification that may have been required for using it.\n\nNote that a delegate user must be referred to by their primary email\naddress, and not an email alias.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority."
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority."
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.get",
                  "description": "Gets the specified delegate.\n\nNote that a delegate user must be referred to by their primary email\naddress, and not an email alias.\n\nThis method is only available to service account clients that have been\ndelegated domain-wide authority."
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.create",
                  "description": "Adds a delegate with its verification status set directly to\n\u003ccode\u003eaccepted\u003c/code\u003e, without sending any verification email.  The\ndelegate user must be a member of the same G Suite organization as the\ndelegator user.\n\nGmail imposes limitations on the number of delegates and delegators each\nuser in a G Suite organization can have. These limits depend on your\norganization, but in general each user can have up to 25 delegates and\nup to 10[...]",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates"
                }
              }
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list",
              "path": "gmail/v1/users/{userId}/history",
              "description": "Lists the history of all changes to the given mailbox. History results are\nreturned in chronological order (increasing \u003ccode\u003ehistoryId\u003c/code\u003e)."
            }
          }
        },
        "labels": {
          "methods": {
            "patch": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.patch",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Patch the specified label.",
              "httpMethod": "PATCH"
            },
            "get": {
              "description": "Gets the specified label.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.get",
              "path": "gmail/v1/users/{userId}/labels/{id}"
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.update",
              "description": "Updates the specified label."
            },
            "delete": {
              "id": "gmail.users.labels.delete",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Immediately and permanently deletes the specified label and removes it from\nany messages and threads that it is applied to.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.list",
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Lists all labels in the user's mailbox."
            },
            "create": {
              "path": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.create",
              "description": "Creates a new label.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels"
            }
          }
        },
        "messages": {
          "methods": {
            "delete": {
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.delete",
              "description": "Immediately and permanently deletes the specified message. This operation\ncannot be undone.  Prefer \u003ccode\u003emessages.trash\u003c/code\u003e instead.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "import": {
              "id": "gmail.users.messages.import",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "path": "gmail/v1/users/{userId}/messages/import",
              "description": "Imports a message into only this user's mailbox, with standard\nemail delivery scanning and classification similar to receiving via SMTP.\nDoes not send a message.",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "description": "Lists the messages in the user's mailbox.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.list",
              "path": "gmail/v1/users/{userId}/messages"
            },
            "trash": {
              "description": "Moves the specified message to the trash.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "id": "gmail.users.messages.trash"
            },
            "batchModify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "id": "gmail.users.messages.batchModify",
              "description": "Modifies the labels on the specified messages.",
              "httpMethod": "POST"
            },
            "batchDelete": {
              "id": "gmail.users.messages.batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "description": "Deletes many messages by message ID.  Provides no guarantees that messages\nwere not already deleted or even existed at all.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete"
            },
            "insert": {
              "description": "Directly inserts a message into only this user's mailbox similar to\n\u003ccode\u003eIMAP APPEND\u003c/code\u003e, bypassing most scanning and classification.\nDoes not send a message.",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.insert",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.get",
              "description": "Gets the specified message."
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "path": "gmail/v1/users/{userId}/messages/send",
              "description": "Sends the specified message to the recipients in the\n\u003ccode\u003eTo\u003c/code\u003e, \u003ccode\u003eCc\u003c/code\u003e, and \u003ccode\u003eBcc\u003c/code\u003e headers.",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "id": "gmail.users.messages.send"
            },
            "modify": {
              "description": "Modifies the labels on the specified message.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "id": "gmail.users.messages.modify",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify"
            },
            "untrash": {
              "description": "Removes the specified message from the trash.",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash"
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get"
                }
              }
            }
          }
        },
        "drafts": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list",
              "description": "Lists the drafts in the user's mailbox."
            },
            "create": {
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "path": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a new draft with the \u003ccode\u003eDRAFT\u003c/code\u003e label.",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.create"
            },
            "get": {
              "description": "Gets the specified draft.",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get"
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "description": "Sends the specified, existing draft to the recipients in the\n\u003ccode\u003eTo\u003c/code\u003e, \u003ccode\u003eCc\u003c/code\u003e, and \u003ccode\u003eBcc\u003c/code\u003e headers.",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.send"
            },
            "update": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Replaces a draft's content.",
              "supportsMediaUpload": true,
              "httpMethod": "PUT",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.update"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.delete",
              "description": "Immediately and permanently deletes the specified draft.\nDoes not simply trash it."
            }
          }
        }
      }
    }
  }
}
