{
  "version_module": true,
  "basePath": "",
  "servicePath": "",
  "version": "v1",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "name": "displayvideo",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "revision": "20200806",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "title": "Display & Video 360 API",
  "canonicalName": "Display Video",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "New Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "baseUrl": "https://displayvideo.googleapis.com/",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "id": "displayvideo:v1",
  "resources": {
    "combinedAudiences": {
      "methods": {
        "list": {
          "id": "displayvideo.combinedAudiences.list",
          "path": "v1/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "flatPath": "v1/combinedAudiences"
        },
        "get": {
          "flatPath": "v1/combinedAudiences/{combinedAudiencesId}",
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/combinedAudiences/{+combinedAudienceId}"
        }
      }
    },
    "inventorySources": {
      "methods": {
        "get": {
          "id": "displayvideo.inventorySources.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/inventorySources/{inventorySourcesId}",
          "path": "v1/inventorySources/{+inventorySourceId}",
          "description": "Gets an inventory source."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v1/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/inventorySources",
          "id": "displayvideo.inventorySources.list"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "flatPath": "v1/floodlightGroups/{floodlightGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "id": "displayvideo.floodlightGroups.get",
          "path": "v1/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "flatPath": "v1/floodlightGroups/{floodlightGroupId}",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "id": "displayvideo.floodlightGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "httpMethod": "PATCH"
        }
      }
    },
    "sdfdownloadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "flatPath": "v1/sdfdownloadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "path": "v1/{+name}"
            }
          }
        }
      },
      "methods": {
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.sdfdownloadtasks.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "path": "v1/sdfdownloadtasks",
          "flatPath": "v1/sdfdownloadtasks"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "path": "download/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "flatPath": "download/{downloadId}"
        }
      }
    },
    "users": {
      "methods": {
        "delete": {
          "path": "v1/users/{+userId}",
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Deletes a user.",
          "httpMethod": "DELETE",
          "flatPath": "v1/users/{usersId}"
        },
        "bulkEditAssignedUserRoles": {
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users/{usersId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST"
        },
        "list": {
          "id": "displayvideo.users.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v1/users",
          "path": "v1/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "httpMethod": "GET"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v1/users",
          "httpMethod": "POST",
          "flatPath": "v1/users",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "id": "displayvideo.users.create"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1/users/{usersId}",
          "description": "Updates an existing user. Returns the updated user if successful.",
          "path": "v1/users/{+userId}",
          "id": "displayvideo.users.patch"
        },
        "get": {
          "id": "displayvideo.users.get",
          "flatPath": "v1/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Gets a user.",
          "path": "v1/users/{+userId}",
          "httpMethod": "GET"
        }
      }
    },
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "httpMethod": "POST",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            },
            "list": {
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "delete": {
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete"
            },
            "create": {
              "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "httpMethod": "POST",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v1/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "flatPath": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v1/inventorySourceGroups"
        },
        "delete": {
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "description": "Deletes an inventory source group.",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupsId}",
          "description": "Gets an inventory source group.",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "httpMethod": "PATCH",
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.get",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "description": "Gets a Google audience.",
          "httpMethod": "GET",
          "flatPath": "v1/googleAudiences/{googleAudiencesId}"
        },
        "list": {
          "flatPath": "v1/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.list",
          "path": "v1/googleAudiences"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "get": {
          "description": "Gets a first and third party audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "httpMethod": "GET"
        },
        "list": {
          "path": "v1/firstAndThirdPartyAudiences",
          "flatPath": "v1/firstAndThirdPartyAudiences",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "partners": {
      "resources": {
        "channels": {
          "methods": {
            "patch": {
              "flatPath": "v1/partners/{partnersId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v1/partners/{partnersId}/channels/{channelsId}",
              "id": "displayvideo.partners.channels.get",
              "httpMethod": "GET",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}"
            },
            "create": {
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "flatPath": "v1/partners/{partnersId}/channels",
              "path": "v1/partners/{+partnerId}/channels"
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/partners/{+partnerId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.list",
              "flatPath": "v1/partners/{partnersId}/channels"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v1/partners/{partnersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.partners.channels.sites.list"
                },
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}"
                },
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/partners/{partnerId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "httpMethod": "POST",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful."
                },
                "get": {
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete"
                }
              }
            }
          }
        }
      },
      "methods": {
        "bulkEditPartnerAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/partners/{partnersId}:bulkEditPartnerAssignedTargetingOptions",
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.get",
          "path": "v1/partners/{+partnerId}",
          "description": "Gets a partner.",
          "flatPath": "v1/partners/{partnersId}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "v1/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/partners",
          "httpMethod": "GET"
        }
      }
    },
    "advertisers": {
      "methods": {
        "bulkListAdvertiserAssignedTargetingOptions": {
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkListAdvertiserAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v1/advertisers",
          "path": "v1/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported."
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "httpMethod": "DELETE",
          "path": "v1/advertisers/{+advertiserId}",
          "flatPath": "v1/advertisers/{advertisersId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "flatPath": "v1/advertisers",
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v1/advertisers",
          "id": "displayvideo.advertisers.create"
        },
        "patch": {
          "path": "v1/advertisers/{+advertiserId}",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets an advertiser.",
          "id": "displayvideo.advertisers.get",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "GET",
          "flatPath": "v1/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "audit": {
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v1/advertisers/{advertisersId}:audit",
          "path": "v1/advertisers/{+advertiserId}:audit"
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "flatPath": "v1/advertisers/{advertisersId}:bulkEditAdvertiserAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests ."
        }
      },
      "resources": {
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST"
                },
                "delete": {
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}/sites"
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v1/advertisers/{advertiserId}/channels/{channelsId}/sites"
                }
              }
            }
          },
          "methods": {
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "id": "displayvideo.advertisers.channels.create"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.get",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelsId}"
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/channels",
              "id": "displayvideo.advertisers.channels.list",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v1/advertisers/{advertisersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful."
            }
          }
        },
        "creatives": {
          "methods": {
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "delete": {
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful."
            },
            "patch": {
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "flatPath": "v1/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/advertisers/{advertisersId}/creatives",
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "list": {
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list."
                },
                "bulkEdit": {
                  "flatPath": "v1/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "httpMethod": "POST"
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "patch": {
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch"
            },
            "create": {
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.create",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful."
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos.",
              "path": "v1/advertisers/{+advertiserId}/assets",
              "id": "displayvideo.advertisers.assets.upload",
              "supportsMediaUpload": true,
              "flatPath": "v1/advertisers/{advertisersId}/assets",
              "httpMethod": "POST"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete"
                },
                "get": {
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v1/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                }
              }
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "description": "Creates an assignment between a location and a location list."
                },
                "delete": {
                  "description": "Deletes the assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete"
                },
                "list": {
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list"
                },
                "bulkEdit": {
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "flatPath": "v1/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST"
                }
              }
            }
          },
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "id": "displayvideo.advertisers.locationLists.create"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v1/advertisers/{advertisersId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful."
            }
          }
        },
        "campaigns": {
          "methods": {
            "delete": {
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/campaigns"
            },
            "patch": {
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}"
            },
            "list": {
              "id": "displayvideo.advertisers.campaigns.list",
              "flatPath": "v1/advertisers/{advertisersId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "get": {
              "flatPath": "v1/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get",
              "httpMethod": "GET"
            }
          }
        },
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Deletes an assigned targeting option from a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "list": {
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "get": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "bulkListLineItemAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkListLineItemAssignedTargetingOptions"
            },
            "list": {
              "id": "displayvideo.advertisers.lineItems.list",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "httpMethod": "GET",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "get": {
              "description": "Gets a line item.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.patch",
              "description": "Updates an existing line item. Returns the updated line item if successful.",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "create": {
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "id": "displayvideo.advertisers.lineItems.create",
              "httpMethod": "POST",
              "flatPath": "v1/advertisers/{advertisersId}/lineItems"
            },
            "bulkEditLineItemAssignedTargetingOptions": {
              "flatPath": "v1/advertisers/{advertisersId}/lineItems/{lineItemsId}:bulkEditLineItemAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests ."
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "description": "Lists targeting options of a given type.",
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions"
            },
            "get": {
              "flatPath": "v1/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "description": "Gets a single targeting option.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "id": "displayvideo.targetingTypes.targetingOptions.get"
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "flatPath": "v1/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom bidding algorithm."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v1/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "flatPath": "v1/customBiddingAlgorithms"
        }
      }
    },
    "customLists": {
      "methods": {
        "list": {
          "id": "displayvideo.customLists.list",
          "flatPath": "v1/customLists",
          "httpMethod": "GET",
          "path": "v1/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom lists. The order is defined by the order_by parameter."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v1/customLists/{+customListId}",
          "flatPath": "v1/customLists/{customListsId}",
          "id": "displayvideo.customLists.get",
          "description": "Gets a custom list."
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/display-video/",
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports."
}
