{
  "basePath": "",
  "documentationLink": "https://developers.google.com/google-apps/reseller/",
  "ownerName": "Google",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "protocol": "rest",
  "description": "Perform common functions that are available on the Google Apps Reseller Console at scale like placing orders and viewing customer information",
  "title": "Google Apps Reseller API",
  "servicePath": "",
  "version": "v1",
  "baseUrl": "https://www.googleapis.com/",
  "kind": "discovery#restDescription",
  "name": "reseller",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "resources": {
    "subscriptions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "description": "Get a specific subscription.",
          "httpMethod": "GET",
          "id": "reseller.subscriptions.get",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}"
        },
        "startPaidService": {
          "httpMethod": "POST",
          "id": "reseller.subscriptions.startPaidService",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/startPaidService",
          "description": "Immediately move a 30-day free trial subscription to a paid service\nsubscription."
        },
        "changeRenewalSettings": {
          "id": "reseller.subscriptions.changeRenewalSettings",
          "description": "Update a user license&#39;s renewal settings. This is applicable for\naccounts with annual commitment plans only.",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeRenewalSettings"
        },
        "changePlan": {
          "id": "reseller.subscriptions.changePlan",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Update a subscription plan. Use this method to update a plan for a 30-day\ntrial or a flexible plan subscription to an annual commitment plan with\nmonthly or yearly payments.",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changePlan",
          "httpMethod": "POST"
        },
        "activate": {
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/activate",
          "description": "Activates a subscription previously suspended by the reseller",
          "id": "reseller.subscriptions.activate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ]
        },
        "list": {
          "path": "apps/reseller/v1/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "description": "List of subscriptions managed by the reseller. The list can be all\nsubscriptions, all of a customer&#39;s subscriptions, or all of a\ncustomer&#39;s transferable subscriptions.",
          "httpMethod": "GET",
          "flatPath": "apps/reseller/v1/subscriptions",
          "id": "reseller.subscriptions.list"
        },
        "delete": {
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "id": "reseller.subscriptions.delete",
          "description": "Cancel, suspend, or transfer a subscription to direct.",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}",
          "httpMethod": "DELETE"
        },
        "changeSeats": {
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
          "description": "Update a subscription&#39;s user license settings.",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/changeSeats",
          "id": "reseller.subscriptions.changeSeats",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "httpMethod": "POST"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions",
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions",
          "id": "reseller.subscriptions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Create or transfer a subscription."
        },
        "suspend": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "path": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend",
          "httpMethod": "POST",
          "id": "reseller.subscriptions.suspend",
          "flatPath": "apps/reseller/v1/customers/{customerId}/subscriptions/{subscriptionId}/suspend",
          "description": "Suspends an active subscription."
        }
      }
    },
    "customers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Get a customer account.",
          "id": "reseller.customers.get",
          "path": "apps/reseller/v1/customers/{customerId}",
          "flatPath": "apps/reseller/v1/customers/{customerId}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ]
        },
        "patch": {
          "path": "apps/reseller/v1/customers/{customerId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Patch a customer account's settings via Apiary Patch Orchestration",
          "id": "reseller.customers.patch",
          "flatPath": "apps/reseller/v1/customers/{customerId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "flatPath": "apps/reseller/v1/customers/{customerId}",
          "description": "Update a customer account's settings.",
          "id": "reseller.customers.update",
          "path": "apps/reseller/v1/customers/{customerId}",
          "httpMethod": "PUT"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "apps/reseller/v1/customers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "id": "reseller.customers.insert",
          "description": "Order a new customer's account.",
          "flatPath": "apps/reseller/v1/customers"
        }
      }
    },
    "resellernotify": {
      "methods": {
        "getwatchdetails": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order",
            "https://www.googleapis.com/auth/apps.order.readonly"
          ],
          "flatPath": "apps/reseller/v1/resellernotify/getwatchdetails",
          "description": "Returns all the details of the watch corresponding to the reseller.",
          "id": "reseller.resellernotify.getwatchdetails",
          "path": "apps/reseller/v1/resellernotify/getwatchdetails",
          "httpMethod": "GET"
        },
        "register": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "id": "reseller.resellernotify.register",
          "httpMethod": "POST",
          "path": "apps/reseller/v1/resellernotify/register",
          "flatPath": "apps/reseller/v1/resellernotify/register",
          "description": "Registers a Reseller for receiving notifications."
        },
        "unregister": {
          "id": "reseller.resellernotify.unregister",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Unregisters a Reseller for receiving notifications.",
          "flatPath": "apps/reseller/v1/resellernotify/unregister",
          "path": "apps/reseller/v1/resellernotify/unregister",
          "httpMethod": "POST"
        }
      }
    }
  },
  "canonicalName": "Reseller",
  "batchPath": "batch/reseller/v1",
  "id": "reseller:v1",
  "revision": "20200627",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/apps.order.readonly": {
          "description": "Manage users on your domain"
        },
        "https://www.googleapis.com/auth/apps.order": {
          "description": "Manage users on your domain"
        }
      }
    }
  }
}
