/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.merchantapi.accounts_v1.model;

/**
 * Request message for the RegisterGCP method.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Merchant API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RegisterGcpRequest extends com.google.api.client.json.GenericJson {

  /**
   * Immutable. If the developer email provided is associated with a user in the merchant account
   * provided, the user will be updated to have "API developer" access type and the email preference
   * corresponding to that user will be updated to have the new "API notifications" preference. If
   * the developer email provided is not associated with any user we will just add it as a contact.
   * The email preference corresponding to that contact will have the new "API notifications"
   * preference
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String developerEmail;

  /**
   * Immutable. If the developer email provided is associated with a user in the merchant account
   * provided, the user will be updated to have "API developer" access type and the email preference
   * corresponding to that user will be updated to have the new "API notifications" preference. If
   * the developer email provided is not associated with any user we will just add it as a contact.
   * The email preference corresponding to that contact will have the new "API notifications"
   * preference
   * @return value or {@code null} for none
   */
  public java.lang.String getDeveloperEmail() {
    return developerEmail;
  }

  /**
   * Immutable. If the developer email provided is associated with a user in the merchant account
   * provided, the user will be updated to have "API developer" access type and the email preference
   * corresponding to that user will be updated to have the new "API notifications" preference. If
   * the developer email provided is not associated with any user we will just add it as a contact.
   * The email preference corresponding to that contact will have the new "API notifications"
   * preference
   * @param developerEmail developerEmail or {@code null} for none
   */
  public RegisterGcpRequest setDeveloperEmail(java.lang.String developerEmail) {
    this.developerEmail = developerEmail;
    return this;
  }

  @Override
  public RegisterGcpRequest set(String fieldName, Object value) {
    return (RegisterGcpRequest) super.set(fieldName, value);
  }

  @Override
  public RegisterGcpRequest clone() {
    return (RegisterGcpRequest) super.clone();
  }

}
