/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.remotebuildexecution.v2.model;

/**
 * Model definition for GoogleDevtoolsRemotebuildbotResourceUsageIOStats.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Remote Build Execution API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleDevtoolsRemotebuildbotResourceUsageIOStats extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger readBytesCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger readCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger readTimeMs;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger writeBytesCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger writeCount;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger writeTimeMs;

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getReadBytesCount() {
    return readBytesCount;
  }

  /**
   * @param readBytesCount readBytesCount or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setReadBytesCount(java.math.BigInteger readBytesCount) {
    this.readBytesCount = readBytesCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getReadCount() {
    return readCount;
  }

  /**
   * @param readCount readCount or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setReadCount(java.math.BigInteger readCount) {
    this.readCount = readCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getReadTimeMs() {
    return readTimeMs;
  }

  /**
   * @param readTimeMs readTimeMs or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setReadTimeMs(java.math.BigInteger readTimeMs) {
    this.readTimeMs = readTimeMs;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getWriteBytesCount() {
    return writeBytesCount;
  }

  /**
   * @param writeBytesCount writeBytesCount or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setWriteBytesCount(java.math.BigInteger writeBytesCount) {
    this.writeBytesCount = writeBytesCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getWriteCount() {
    return writeCount;
  }

  /**
   * @param writeCount writeCount or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setWriteCount(java.math.BigInteger writeCount) {
    this.writeCount = writeCount;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getWriteTimeMs() {
    return writeTimeMs;
  }

  /**
   * @param writeTimeMs writeTimeMs or {@code null} for none
   */
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats setWriteTimeMs(java.math.BigInteger writeTimeMs) {
    this.writeTimeMs = writeTimeMs;
    return this;
  }

  @Override
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats set(String fieldName, Object value) {
    return (GoogleDevtoolsRemotebuildbotResourceUsageIOStats) super.set(fieldName, value);
  }

  @Override
  public GoogleDevtoolsRemotebuildbotResourceUsageIOStats clone() {
    return (GoogleDevtoolsRemotebuildbotResourceUsageIOStats) super.clone();
  }

}
