/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.beyondcorp.v1alpha.model;

/**
 * The configuration that was applied to generate the result.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the BeyondCorp API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Aggregation type applied.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String aggregation;

  /**
   * Output only. Customised grouping applied.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudBeyondcorpSaasplatformInsightsV1alphaCustomGrouping customGrouping;

  /**
   * Output only. Ending time for the duration for which insight was pulled.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String endTime;

  /**
   * Output only. Filters applied.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fieldFilter;

  /**
   * Output only. Group id of the grouping applied.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String group;

  /**
   * Output only. Starting time for the duration for which insight was pulled.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String startTime;

  /**
   * Output only. Aggregation type applied.
   * @return value or {@code null} for none
   */
  public java.lang.String getAggregation() {
    return aggregation;
  }

  /**
   * Output only. Aggregation type applied.
   * @param aggregation aggregation or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setAggregation(java.lang.String aggregation) {
    this.aggregation = aggregation;
    return this;
  }

  /**
   * Output only. Customised grouping applied.
   * @return value or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaCustomGrouping getCustomGrouping() {
    return customGrouping;
  }

  /**
   * Output only. Customised grouping applied.
   * @param customGrouping customGrouping or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setCustomGrouping(GoogleCloudBeyondcorpSaasplatformInsightsV1alphaCustomGrouping customGrouping) {
    this.customGrouping = customGrouping;
    return this;
  }

  /**
   * Output only. Ending time for the duration for which insight was pulled.
   * @return value or {@code null} for none
   */
  public String getEndTime() {
    return endTime;
  }

  /**
   * Output only. Ending time for the duration for which insight was pulled.
   * @param endTime endTime or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setEndTime(String endTime) {
    this.endTime = endTime;
    return this;
  }

  /**
   * Output only. Filters applied.
   * @return value or {@code null} for none
   */
  public java.lang.String getFieldFilter() {
    return fieldFilter;
  }

  /**
   * Output only. Filters applied.
   * @param fieldFilter fieldFilter or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setFieldFilter(java.lang.String fieldFilter) {
    this.fieldFilter = fieldFilter;
    return this;
  }

  /**
   * Output only. Group id of the grouping applied.
   * @return value or {@code null} for none
   */
  public java.lang.String getGroup() {
    return group;
  }

  /**
   * Output only. Group id of the grouping applied.
   * @param group group or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setGroup(java.lang.String group) {
    this.group = group;
    return this;
  }

  /**
   * Output only. Starting time for the duration for which insight was pulled.
   * @return value or {@code null} for none
   */
  public String getStartTime() {
    return startTime;
  }

  /**
   * Output only. Starting time for the duration for which insight was pulled.
   * @param startTime startTime or {@code null} for none
   */
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig setStartTime(String startTime) {
    this.startTime = startTime;
    return this;
  }

  @Override
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig set(String fieldName, Object value) {
    return (GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig clone() {
    return (GoogleCloudBeyondcorpSaasplatformInsightsV1alphaAppliedConfig) super.clone();
  }

}
