/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.drivelabels.v2.model;

/**
 * Request to disable the field.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Drive Labels API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest extends com.google.api.client.json.GenericJson {

  /**
   * Required. Field disabled policy.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleAppsDriveLabelsV2LifecycleDisabledPolicy disabledPolicy;

  /**
   * Required. Key of the field to disable.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The fields that should be updated. At least one field must be specified. The root
   * `disabled_policy` is implied and should not be specified. A single `*` can be used as a short-
   * hand for updating every field.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String updateMask;

  /**
   * Required. Field disabled policy.
   * @return value or {@code null} for none
   */
  public GoogleAppsDriveLabelsV2LifecycleDisabledPolicy getDisabledPolicy() {
    return disabledPolicy;
  }

  /**
   * Required. Field disabled policy.
   * @param disabledPolicy disabledPolicy or {@code null} for none
   */
  public GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest setDisabledPolicy(GoogleAppsDriveLabelsV2LifecycleDisabledPolicy disabledPolicy) {
    this.disabledPolicy = disabledPolicy;
    return this;
  }

  /**
   * Required. Key of the field to disable.
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Required. Key of the field to disable.
   * @param id id or {@code null} for none
   */
  public GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * The fields that should be updated. At least one field must be specified. The root
   * `disabled_policy` is implied and should not be specified. A single `*` can be used as a short-
   * hand for updating every field.
   * @return value or {@code null} for none
   */
  public String getUpdateMask() {
    return updateMask;
  }

  /**
   * The fields that should be updated. At least one field must be specified. The root
   * `disabled_policy` is implied and should not be specified. A single `*` can be used as a short-
   * hand for updating every field.
   * @param updateMask updateMask or {@code null} for none
   */
  public GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest setUpdateMask(String updateMask) {
    this.updateMask = updateMask;
    return this;
  }

  @Override
  public GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest set(String fieldName, Object value) {
    return (GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest) super.set(fieldName, value);
  }

  @Override
  public GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest clone() {
    return (GoogleAppsDriveLabelsV2DeltaUpdateLabelRequestDisableFieldRequest) super.clone();
  }

}
