{
  "discoveryVersion": "v1",
  "revision": "20201016",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        }
      }
    }
  },
  "protocol": "rest",
  "basePath": "",
  "id": "games:v1",
  "baseUrl": "https://games.googleapis.com/",
  "rootUrl": "https://games.googleapis.com/",
  "version": "v1",
  "documentationLink": "https://developers.google.com/games/",
  "title": "Google Play Game Services",
  "canonicalName": "Games",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "batchPath": "batch",
  "name": "games",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "resources": {
    "revisions": {
      "methods": {
        "check": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check",
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "description": "Checks whether the games client is out of date.",
          "flatPath": "games/v1/revisions/check"
        }
      }
    },
    "scores": {
      "methods": {
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "path": "games/v1/leaderboards/scores",
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards."
        },
        "list": {
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list"
        },
        "get": {
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "id": "games.scores.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submit": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.submit"
        },
        "listWindow": {
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "httpMethod": "GET",
          "id": "games.scores.listWindow",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.list",
          "httpMethod": "GET",
          "path": "games/v1/players/me/players/{collection}"
        },
        "get": {
          "id": "games.players.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "flatPath": "games/v1/players/{playerId}"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "path": "games/v1/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application.",
          "id": "games.achievementDefinitions.list"
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "id": "games.snapshots.list",
          "path": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "id": "games.snapshots.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "path": "games/v1/snapshots/{snapshotId}"
        }
      }
    },
    "applications": {
      "methods": {
        "played": {
          "flatPath": "games/v1/applications/played",
          "path": "games/v1/applications/played",
          "httpMethod": "POST",
          "id": "games.applications.played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Indicate that the currently authenticated user is playing your application."
        },
        "verify": {
          "path": "games/v1/applications/{applicationId}/verify",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET"
        },
        "get": {
          "id": "games.applications.get",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "flatPath": "games/v1/applications/{applicationId}",
          "path": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "achievements": {
      "methods": {
        "list": {
          "flatPath": "games/v1/players/{playerId}/achievements",
          "path": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player."
        },
        "unlock": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock",
          "description": "Unlocks this achievement for the currently authenticated player."
        },
        "updateMultiple": {
          "path": "games/v1/achievements/updateMultiple",
          "id": "games.achievements.updateMultiple",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player."
        },
        "setStepsAtLeast": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "reveal": {
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/reveal"
        },
        "increment": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "id": "games.achievements.increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment"
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "httpMethod": "GET",
          "flatPath": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "id": "games.events.listDefinitions",
          "path": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "httpMethod": "POST",
          "id": "games.events.record"
        },
        "listByPlayer": {
          "path": "games/v1/events",
          "id": "games.events.listByPlayer",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "flatPath": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.get",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "path": "games/v1/leaderboards/{leaderboardId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "path": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.stats.get"
        }
      }
    },
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/categories/{collection}"
        },
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "flatPath": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application."
        }
      }
    }
  }
}
