{
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/games/",
  "baseUrl": "https://www.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "name": "games",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards,\n    achievements, game state, sign-in with Google, and more.",
  "kind": "discovery#restDescription",
  "canonicalName": "Games",
  "discoveryVersion": "v1",
  "revision": "20200625",
  "title": "Google Play Game Services",
  "resources": {
    "metagame": {
      "methods": {
        "listCategoriesByPlayer": {
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer",
          "description": "List play data aggregated per category for the player corresponding to\n`playerId`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "getMetagameConfig": {
          "path": "games/v1/metagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "flatPath": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "description": "Lists all the leaderboard metadata for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards",
          "id": "games.leaderboards.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards"
        },
        "get": {
          "id": "games.leaderboards.get",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "path": "games/v1/leaderboards/{leaderboardId}"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "games/v1/achievements",
          "id": "games.achievementDefinitions.list",
          "flatPath": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the achievement definitions for your application."
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently\nauthenticated player.  For a specific time span, `leaderboardId`\ncan be set to `ALL` to retrieve data for all leaderboards in a\ngiven time span.  `NOTE: You cannot ask for 'ALL' leaderboards and\n'ALL' timeSpans in the same request; only one parameter may be set to\n'ALL'.",
          "httpMethod": "GET"
        },
        "submit": {
          "httpMethod": "POST",
          "description": "Submits a score to the specified leaderboard.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.submit",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top."
        },
        "submitMultiple": {
          "description": "Submits multiple scores to leaderboards.",
          "path": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "id": "games.scores.submitMultiple"
        },
        "listWindow": {
          "id": "games.scores.listWindow",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard around (and including) a player's score."
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "httpMethod": "GET",
          "description": "Checks whether the games client is out of date.",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.revisions.check",
          "path": "games/v1/revisions/check"
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "path": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "flatPath": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listByPlayer": {
          "flatPath": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application\nfor the currently authenticated user.",
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "record": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for\nthe currently authenticated user of this application.",
          "httpMethod": "POST",
          "id": "games.events.record"
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "description": "Get the collection of players for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/me/players/{collection}",
          "flatPath": "games/v1/players/me/players/{collection}",
          "id": "games.players.list",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID.  To retrieve the player\nfor the currently authenticated user, set `playerId` to `me`.",
          "id": "games.players.get",
          "flatPath": "games/v1/players/{playerId}"
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "description": "Verifies the auth token provided with this request is for the application\nwith the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.verify"
        },
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the\nrequested application is not available for the specified\n`platformType`, the returned response will not include any\ninstance data.",
          "flatPath": "games/v1/applications/{applicationId}",
          "path": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.get",
          "httpMethod": "GET"
        },
        "played": {
          "flatPath": "games/v1/applications/played",
          "id": "games.applications.played",
          "path": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Indicate that the currently authenticated user is playing your\napplication.",
          "httpMethod": "POST"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/snapshots/{snapshotId}",
          "flatPath": "games/v1/snapshots/{snapshotId}"
        },
        "list": {
          "id": "games.snapshots.list",
          "description": "Retrieves a list of snapshots created by your application for the player\ncorresponding to the player ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/snapshots",
          "flatPath": "games/v1/players/{playerId}/snapshots"
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "path": "games/v1/achievements/{achievementId}/increment",
          "description": "Increments the steps of the achievement with the given ID for the currently\nauthenticated player.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "id": "games.achievements.increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "unlock": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "description": "Lists the progress for all your application's achievements for the\ncurrently authenticated player.",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/achievements"
        },
        "updateMultiple": {
          "description": "Updates multiple achievements for the currently authenticated player.",
          "path": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "id": "games.achievements.updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "reveal": {
          "httpMethod": "POST",
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to\n`REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/reveal"
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an\nachievement. If the steps parameter is less than the current number of\nsteps that the player already gained for the achievement, the achievement\nis not modified."
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "path": "games/v1/stats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns engagement and spend statistics in this application for the\ncurrently authenticated user.",
          "flatPath": "games/v1/stats",
          "id": "games.stats.get"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "basePath": "",
  "protocol": "rest",
  "servicePath": "",
  "id": "games:v1",
  "ownerName": "Google",
  "rootUrl": "https://www.googleapis.com/",
  "batchPath": "batch/games/v1",
  "version": "v1"
}
