/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.dns.model;

/**
 * Model definition for PolicyAlternativeNameServerConfig.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud DNS API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PolicyAlternativeNameServerConfig extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kind;

  /**
   * Sets an alternative name server for the associated networks. When specified, all DNS queries
   * are forwarded to a name server that you choose. Names such as .internal are not available when
   * an alternative name server is specified.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<PolicyAlternativeNameServerConfigTargetNameServer> targetNameServers;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKind() {
    return kind;
  }

  /**
   * @param kind kind or {@code null} for none
   */
  public PolicyAlternativeNameServerConfig setKind(java.lang.String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Sets an alternative name server for the associated networks. When specified, all DNS queries
   * are forwarded to a name server that you choose. Names such as .internal are not available when
   * an alternative name server is specified.
   * @return value or {@code null} for none
   */
  public java.util.List<PolicyAlternativeNameServerConfigTargetNameServer> getTargetNameServers() {
    return targetNameServers;
  }

  /**
   * Sets an alternative name server for the associated networks. When specified, all DNS queries
   * are forwarded to a name server that you choose. Names such as .internal are not available when
   * an alternative name server is specified.
   * @param targetNameServers targetNameServers or {@code null} for none
   */
  public PolicyAlternativeNameServerConfig setTargetNameServers(java.util.List<PolicyAlternativeNameServerConfigTargetNameServer> targetNameServers) {
    this.targetNameServers = targetNameServers;
    return this;
  }

  @Override
  public PolicyAlternativeNameServerConfig set(String fieldName, Object value) {
    return (PolicyAlternativeNameServerConfig) super.set(fieldName, value);
  }

  @Override
  public PolicyAlternativeNameServerConfig clone() {
    return (PolicyAlternativeNameServerConfig) super.clone();
  }

}
