/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.pubsub.model;

/**
 * Settings for an ingestion data source on a topic.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Pub/Sub API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class IngestionDataSourceSettings extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Amazon Kinesis Data Streams.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AwsKinesis awsKinesis;

  /**
   * Optional. Cloud Storage.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CloudStorage cloudStorage;

  /**
   * Optional. Platform Logs settings. If unset, no Platform Logs will be generated.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private PlatformLogsSettings platformLogsSettings;

  /**
   * Optional. Amazon Kinesis Data Streams.
   * @return value or {@code null} for none
   */
  public AwsKinesis getAwsKinesis() {
    return awsKinesis;
  }

  /**
   * Optional. Amazon Kinesis Data Streams.
   * @param awsKinesis awsKinesis or {@code null} for none
   */
  public IngestionDataSourceSettings setAwsKinesis(AwsKinesis awsKinesis) {
    this.awsKinesis = awsKinesis;
    return this;
  }

  /**
   * Optional. Cloud Storage.
   * @return value or {@code null} for none
   */
  public CloudStorage getCloudStorage() {
    return cloudStorage;
  }

  /**
   * Optional. Cloud Storage.
   * @param cloudStorage cloudStorage or {@code null} for none
   */
  public IngestionDataSourceSettings setCloudStorage(CloudStorage cloudStorage) {
    this.cloudStorage = cloudStorage;
    return this;
  }

  /**
   * Optional. Platform Logs settings. If unset, no Platform Logs will be generated.
   * @return value or {@code null} for none
   */
  public PlatformLogsSettings getPlatformLogsSettings() {
    return platformLogsSettings;
  }

  /**
   * Optional. Platform Logs settings. If unset, no Platform Logs will be generated.
   * @param platformLogsSettings platformLogsSettings or {@code null} for none
   */
  public IngestionDataSourceSettings setPlatformLogsSettings(PlatformLogsSettings platformLogsSettings) {
    this.platformLogsSettings = platformLogsSettings;
    return this;
  }

  @Override
  public IngestionDataSourceSettings set(String fieldName, Object value) {
    return (IngestionDataSourceSettings) super.set(fieldName, value);
  }

  @Override
  public IngestionDataSourceSettings clone() {
    return (IngestionDataSourceSettings) super.clone();
  }

}
