/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.dialogflow.v2beta1.model;

/**
 * Model definition for GoogleCloudDialogflowCxV3beta1FormParameter.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Dialogflow API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudDialogflowCxV3beta1FormParameter extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudDialogflowCxV3beta1AdvancedSettings advancedSettings;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Object defaultValue;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String displayName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String entityType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudDialogflowCxV3beta1FormParameterFillBehavior fillBehavior;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean isList;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean redact;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean required;

  /**
   * @return value or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1AdvancedSettings getAdvancedSettings() {
    return advancedSettings;
  }

  /**
   * @param advancedSettings advancedSettings or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setAdvancedSettings(GoogleCloudDialogflowCxV3beta1AdvancedSettings advancedSettings) {
    this.advancedSettings = advancedSettings;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Object getDefaultValue() {
    return defaultValue;
  }

  /**
   * @param defaultValue defaultValue or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setDefaultValue(java.lang.Object defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplayName() {
    return displayName;
  }

  /**
   * @param displayName displayName or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setDisplayName(java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEntityType() {
    return entityType;
  }

  /**
   * @param entityType entityType or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setEntityType(java.lang.String entityType) {
    this.entityType = entityType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameterFillBehavior getFillBehavior() {
    return fillBehavior;
  }

  /**
   * @param fillBehavior fillBehavior or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setFillBehavior(GoogleCloudDialogflowCxV3beta1FormParameterFillBehavior fillBehavior) {
    this.fillBehavior = fillBehavior;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getIsList() {
    return isList;
  }

  /**
   * @param isList isList or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setIsList(java.lang.Boolean isList) {
    this.isList = isList;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getRedact() {
    return redact;
  }

  /**
   * @param redact redact or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setRedact(java.lang.Boolean redact) {
    this.redact = redact;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getRequired() {
    return required;
  }

  /**
   * @param required required or {@code null} for none
   */
  public GoogleCloudDialogflowCxV3beta1FormParameter setRequired(java.lang.Boolean required) {
    this.required = required;
    return this;
  }

  @Override
  public GoogleCloudDialogflowCxV3beta1FormParameter set(String fieldName, Object value) {
    return (GoogleCloudDialogflowCxV3beta1FormParameter) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudDialogflowCxV3beta1FormParameter clone() {
    return (GoogleCloudDialogflowCxV3beta1FormParameter) super.clone();
  }

}
