{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "canonicalName": "AnalyticsData",
  "ownerDomain": "google.com",
  "description": "Accesses report data in Google Analytics.",
  "title": "Google Analytics Data API",
  "name": "analyticsdata",
  "basePath": "",
  "revision": "20210314",
  "version_module": true,
  "baseUrl": "https://analyticsdata.googleapis.com/",
  "mtlsRootUrl": "https://analyticsdata.mtls.googleapis.com/",
  "version": "v1alpha",
  "id": "analyticsdata:v1alpha",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/analytics/devguides/reporting/data/v1/",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "resources": {
    "v1alpha": {
      "methods": {
        "batchRunPivotReports": {
          "description": "Returns multiple pivot reports in a batch. All reports must be for the same Entity.",
          "path": "v1alpha:batchRunPivotReports",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsdata.batchRunPivotReports",
          "httpMethod": "POST",
          "flatPath": "v1alpha:batchRunPivotReports"
        },
        "runReport": {
          "path": "v1alpha:runReport",
          "id": "analyticsdata.runReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of your Google Analytics event data. Reports contain statistics derived from data collected by the Google Analytics tracking code. The data returned from the API is as a table with columns for the requested dimensions and metrics. Metrics are individual measurements of user activity on your property, such as active users or event count. Dimensions break down metrics across some common criteria, such as country or event name.",
          "flatPath": "v1alpha:runReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "batchRunReports": {
          "description": "Returns multiple reports in a batch. All reports must be for the same Entity.",
          "path": "v1alpha:batchRunReports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsdata.batchRunReports",
          "flatPath": "v1alpha:batchRunReports"
        },
        "runPivotReport": {
          "flatPath": "v1alpha:runPivotReport",
          "id": "analyticsdata.runPivotReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v1alpha:runPivotReport",
          "description": "Returns a customized pivot report of your Google Analytics event data. Pivot reports are more advanced and expressive formats than regular reports. In a pivot report, dimensions are only visible if they are included in a pivot. Multiple pivots can be specified to further dissect your data."
        }
      }
    },
    "properties": {
      "methods": {
        "runRealtimeReport": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}:runRealtimeReport",
          "path": "v1alpha/{+property}:runRealtimeReport",
          "id": "analyticsdata.properties.runRealtimeReport",
          "description": "The Google Analytics Realtime API returns a customized report of realtime event data for your property. These reports show events and usage from the last 30 minutes."
        },
        "getMetadata": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/metadata",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsdata.properties.getMetadata",
          "description": "Returns metadata for dimensions and metrics available in reporting methods. Used to explore the dimensions and metrics. In this method, a Google Analytics GA4 Property Identifier is specified in the request, and the metadata response includes Custom dimensions and metrics as well as Universal metadata. For example if a custom metric with parameter name `levels_unlocked` is registered to a property, the Metadata response will contain `customEvent:levels_unlocked`. Univer[...]",
          "httpMethod": "GET"
        }
      }
    }
  },
  "servicePath": "",
  "rootUrl": "https://analyticsdata.googleapis.com/"
}
