/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.gkeonprem.v1.model;

/**
 * VmwareVsphereTag describes a vSphere tag to be placed on VMs in the node pool. For more
 * information, see https://docs.vmware.com/en/VMware-
 * vSphere/7.0/com.vmware.vsphere.vcenterhost.doc/GUID-E8E854DD-AA97-4E0C-8419-CE84F93C4058.html
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the GKE On-Prem API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class VmwareVsphereTag extends com.google.api.client.json.GenericJson {

  /**
   * The Vsphere tag category.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String category;

  /**
   * The Vsphere tag name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tag;

  /**
   * The Vsphere tag category.
   * @return value or {@code null} for none
   */
  public java.lang.String getCategory() {
    return category;
  }

  /**
   * The Vsphere tag category.
   * @param category category or {@code null} for none
   */
  public VmwareVsphereTag setCategory(java.lang.String category) {
    this.category = category;
    return this;
  }

  /**
   * The Vsphere tag name.
   * @return value or {@code null} for none
   */
  public java.lang.String getTag() {
    return tag;
  }

  /**
   * The Vsphere tag name.
   * @param tag tag or {@code null} for none
   */
  public VmwareVsphereTag setTag(java.lang.String tag) {
    this.tag = tag;
    return this;
  }

  @Override
  public VmwareVsphereTag set(String fieldName, Object value) {
    return (VmwareVsphereTag) super.set(fieldName, value);
  }

  @Override
  public VmwareVsphereTag clone() {
    return (VmwareVsphereTag) super.clone();
  }

}
