/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.dns.model;

/**
 * Model definition for PolicyAlternativeNameServerConfigOutboundEndpoint.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud DNS API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PolicyAlternativeNameServerConfigOutboundEndpoint extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String kind;

  /**
   * Specified as a resource path including project and region. This should be formatted like
   * projects/{project}/locations/{location}/outboundEndpoints/{endpoint}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getKind() {
    return kind;
  }

  /**
   * @param kind kind or {@code null} for none
   */
  public PolicyAlternativeNameServerConfigOutboundEndpoint setKind(java.lang.String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Specified as a resource path including project and region. This should be formatted like
   * projects/{project}/locations/{location}/outboundEndpoints/{endpoint}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Specified as a resource path including project and region. This should be formatted like
   * projects/{project}/locations/{location}/outboundEndpoints/{endpoint}
   * @param name name or {@code null} for none
   */
  public PolicyAlternativeNameServerConfigOutboundEndpoint setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  @Override
  public PolicyAlternativeNameServerConfigOutboundEndpoint set(String fieldName, Object value) {
    return (PolicyAlternativeNameServerConfigOutboundEndpoint) super.set(fieldName, value);
  }

  @Override
  public PolicyAlternativeNameServerConfigOutboundEndpoint clone() {
    return (PolicyAlternativeNameServerConfigOutboundEndpoint) super.clone();
  }

}
