/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.firestore.v1.model;

/**
 * The specification for how to build a number search index for a field.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Firestore API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirestoreAdminV1SearchNumberSpec extends com.google.api.client.json.GenericJson {

  /**
   * Required. How to index the number field value.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String indexType;

  /**
   * Required. How to index the number field value.
   * @return value or {@code null} for none
   */
  public java.lang.String getIndexType() {
    return indexType;
  }

  /**
   * Required. How to index the number field value.
   * @param indexType indexType or {@code null} for none
   */
  public GoogleFirestoreAdminV1SearchNumberSpec setIndexType(java.lang.String indexType) {
    this.indexType = indexType;
    return this;
  }

  @Override
  public GoogleFirestoreAdminV1SearchNumberSpec set(String fieldName, Object value) {
    return (GoogleFirestoreAdminV1SearchNumberSpec) super.set(fieldName, value);
  }

  @Override
  public GoogleFirestoreAdminV1SearchNumberSpec clone() {
    return (GoogleFirestoreAdminV1SearchNumberSpec) super.clone();
  }

}
