/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.aiplatform.v1.model;

/**
 * Model definition for CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Agent Platform API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Input for video transform (sdedit, diffdiff). Note the input video from the main
   * GenerateVideoRequest will be used as the conditioning.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CloudAiLargeModelsVisionGenerateVideoRequestVideo initializationVideo;

  /**
   * Optional. Mask for video transform (diffdiff).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private CloudAiLargeModelsVisionGenerateVideoRequestVideo mask;

  /**
   * Optional. Noise strength for video transform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float noiseStrength;

  /**
   * Optional. Input for video transform (sdedit, diffdiff). Note the input video from the main
   * GenerateVideoRequest will be used as the conditioning.
   * @return value or {@code null} for none
   */
  public CloudAiLargeModelsVisionGenerateVideoRequestVideo getInitializationVideo() {
    return initializationVideo;
  }

  /**
   * Optional. Input for video transform (sdedit, diffdiff). Note the input video from the main
   * GenerateVideoRequest will be used as the conditioning.
   * @param initializationVideo initializationVideo or {@code null} for none
   */
  public CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform setInitializationVideo(CloudAiLargeModelsVisionGenerateVideoRequestVideo initializationVideo) {
    this.initializationVideo = initializationVideo;
    return this;
  }

  /**
   * Optional. Mask for video transform (diffdiff).
   * @return value or {@code null} for none
   */
  public CloudAiLargeModelsVisionGenerateVideoRequestVideo getMask() {
    return mask;
  }

  /**
   * Optional. Mask for video transform (diffdiff).
   * @param mask mask or {@code null} for none
   */
  public CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform setMask(CloudAiLargeModelsVisionGenerateVideoRequestVideo mask) {
    this.mask = mask;
    return this;
  }

  /**
   * Optional. Noise strength for video transform.
   * @return value or {@code null} for none
   */
  public java.lang.Float getNoiseStrength() {
    return noiseStrength;
  }

  /**
   * Optional. Noise strength for video transform.
   * @param noiseStrength noiseStrength or {@code null} for none
   */
  public CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform setNoiseStrength(java.lang.Float noiseStrength) {
    this.noiseStrength = noiseStrength;
    return this;
  }

  @Override
  public CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform set(String fieldName, Object value) {
    return (CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform) super.set(fieldName, value);
  }

  @Override
  public CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform clone() {
    return (CloudAiLargeModelsVisionGenerateVideoExperimentsVideoTransform) super.clone();
  }

}
