/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.aiplatform.v1.model;

/**
 * Statistics computed for datasets used for reinforcement learning.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Vertex AI API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudAiplatformV1ReinforcementLearningDataStats extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Statistics computed for the preference dataset. This can be either a human
   * preference dataset or a preference dataset generated from AI feedback.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudAiplatformV1DatasetStats preferenceDatasetStats;

  /**
   * Output only. Statistics computed for the prompt dataset used during reinforcement learning.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleCloudAiplatformV1DatasetStats promptDatasetStats;

  /**
   * Output only. Statistics computed for the preference dataset. This can be either a human
   * preference dataset or a preference dataset generated from AI feedback.
   * @return value or {@code null} for none
   */
  public GoogleCloudAiplatformV1DatasetStats getPreferenceDatasetStats() {
    return preferenceDatasetStats;
  }

  /**
   * Output only. Statistics computed for the preference dataset. This can be either a human
   * preference dataset or a preference dataset generated from AI feedback.
   * @param preferenceDatasetStats preferenceDatasetStats or {@code null} for none
   */
  public GoogleCloudAiplatformV1ReinforcementLearningDataStats setPreferenceDatasetStats(GoogleCloudAiplatformV1DatasetStats preferenceDatasetStats) {
    this.preferenceDatasetStats = preferenceDatasetStats;
    return this;
  }

  /**
   * Output only. Statistics computed for the prompt dataset used during reinforcement learning.
   * @return value or {@code null} for none
   */
  public GoogleCloudAiplatformV1DatasetStats getPromptDatasetStats() {
    return promptDatasetStats;
  }

  /**
   * Output only. Statistics computed for the prompt dataset used during reinforcement learning.
   * @param promptDatasetStats promptDatasetStats or {@code null} for none
   */
  public GoogleCloudAiplatformV1ReinforcementLearningDataStats setPromptDatasetStats(GoogleCloudAiplatformV1DatasetStats promptDatasetStats) {
    this.promptDatasetStats = promptDatasetStats;
    return this;
  }

  @Override
  public GoogleCloudAiplatformV1ReinforcementLearningDataStats set(String fieldName, Object value) {
    return (GoogleCloudAiplatformV1ReinforcementLearningDataStats) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudAiplatformV1ReinforcementLearningDataStats clone() {
    return (GoogleCloudAiplatformV1ReinforcementLearningDataStats) super.clone();
  }

}
