/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.integrations.v1.model;

/**
 * Contains the details of the execution info: this includes the replay reason and replay tree
 * connecting executions in a parent-child relationship
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Application Integration API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudIntegrationsV1alphaExecutionReplayInfo extends com.google.api.client.json.GenericJson {

  /**
   * If this execution is a replay of another execution, then this field contains the original
   * execution id.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String originalExecutionInfoId;

  /**
   * Replay mode for the execution
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String replayMode;

  /**
   * reason for replay
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String replayReason;

  /**
   * If this execution has been replayed, then this field contains the execution ids of the replayed
   * executions.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> replayedExecutionInfoIds;

  /**
   * If this execution is a replay of another execution, then this field contains the original
   * execution id.
   * @return value or {@code null} for none
   */
  public java.lang.String getOriginalExecutionInfoId() {
    return originalExecutionInfoId;
  }

  /**
   * If this execution is a replay of another execution, then this field contains the original
   * execution id.
   * @param originalExecutionInfoId originalExecutionInfoId or {@code null} for none
   */
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo setOriginalExecutionInfoId(java.lang.String originalExecutionInfoId) {
    this.originalExecutionInfoId = originalExecutionInfoId;
    return this;
  }

  /**
   * Replay mode for the execution
   * @return value or {@code null} for none
   */
  public java.lang.String getReplayMode() {
    return replayMode;
  }

  /**
   * Replay mode for the execution
   * @param replayMode replayMode or {@code null} for none
   */
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo setReplayMode(java.lang.String replayMode) {
    this.replayMode = replayMode;
    return this;
  }

  /**
   * reason for replay
   * @return value or {@code null} for none
   */
  public java.lang.String getReplayReason() {
    return replayReason;
  }

  /**
   * reason for replay
   * @param replayReason replayReason or {@code null} for none
   */
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo setReplayReason(java.lang.String replayReason) {
    this.replayReason = replayReason;
    return this;
  }

  /**
   * If this execution has been replayed, then this field contains the execution ids of the replayed
   * executions.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getReplayedExecutionInfoIds() {
    return replayedExecutionInfoIds;
  }

  /**
   * If this execution has been replayed, then this field contains the execution ids of the replayed
   * executions.
   * @param replayedExecutionInfoIds replayedExecutionInfoIds or {@code null} for none
   */
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo setReplayedExecutionInfoIds(java.util.List<java.lang.String> replayedExecutionInfoIds) {
    this.replayedExecutionInfoIds = replayedExecutionInfoIds;
    return this;
  }

  @Override
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo set(String fieldName, Object value) {
    return (GoogleCloudIntegrationsV1alphaExecutionReplayInfo) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudIntegrationsV1alphaExecutionReplayInfo clone() {
    return (GoogleCloudIntegrationsV1alphaExecutionReplayInfo) super.clone();
  }

}
