/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.cloudsearch.v1.model;

/**
 * LINT.IfChange The `column` widget can contain these widgets.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Search API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppsDynamiteSharedColumnsColumnWidgets extends com.google.api.client.json.GenericJson {

  /**
   * ButtonList widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedButtonList buttonList;

  /**
   * DateTimePicker widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedDateTimePicker dateTimePicker;

  /**
   * DecoratedText widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedDecoratedText decoratedText;

  /**
   * Image widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedImage image;

  /**
   * SelectionInput widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedSelectionInput selectionInput;

  /**
   * TextInput widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedTextInput textInput;

  /**
   * Text paragraph widget.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsDynamiteSharedTextParagraph textParagraph;

  /**
   * ButtonList widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedButtonList getButtonList() {
    return buttonList;
  }

  /**
   * ButtonList widget.
   * @param buttonList buttonList or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setButtonList(AppsDynamiteSharedButtonList buttonList) {
    this.buttonList = buttonList;
    return this;
  }

  /**
   * DateTimePicker widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedDateTimePicker getDateTimePicker() {
    return dateTimePicker;
  }

  /**
   * DateTimePicker widget.
   * @param dateTimePicker dateTimePicker or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setDateTimePicker(AppsDynamiteSharedDateTimePicker dateTimePicker) {
    this.dateTimePicker = dateTimePicker;
    return this;
  }

  /**
   * DecoratedText widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedDecoratedText getDecoratedText() {
    return decoratedText;
  }

  /**
   * DecoratedText widget.
   * @param decoratedText decoratedText or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setDecoratedText(AppsDynamiteSharedDecoratedText decoratedText) {
    this.decoratedText = decoratedText;
    return this;
  }

  /**
   * Image widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedImage getImage() {
    return image;
  }

  /**
   * Image widget.
   * @param image image or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setImage(AppsDynamiteSharedImage image) {
    this.image = image;
    return this;
  }

  /**
   * SelectionInput widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedSelectionInput getSelectionInput() {
    return selectionInput;
  }

  /**
   * SelectionInput widget.
   * @param selectionInput selectionInput or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setSelectionInput(AppsDynamiteSharedSelectionInput selectionInput) {
    this.selectionInput = selectionInput;
    return this;
  }

  /**
   * TextInput widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedTextInput getTextInput() {
    return textInput;
  }

  /**
   * TextInput widget.
   * @param textInput textInput or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setTextInput(AppsDynamiteSharedTextInput textInput) {
    this.textInput = textInput;
    return this;
  }

  /**
   * Text paragraph widget.
   * @return value or {@code null} for none
   */
  public AppsDynamiteSharedTextParagraph getTextParagraph() {
    return textParagraph;
  }

  /**
   * Text paragraph widget.
   * @param textParagraph textParagraph or {@code null} for none
   */
  public AppsDynamiteSharedColumnsColumnWidgets setTextParagraph(AppsDynamiteSharedTextParagraph textParagraph) {
    this.textParagraph = textParagraph;
    return this;
  }

  @Override
  public AppsDynamiteSharedColumnsColumnWidgets set(String fieldName, Object value) {
    return (AppsDynamiteSharedColumnsColumnWidgets) super.set(fieldName, value);
  }

  @Override
  public AppsDynamiteSharedColumnsColumnWidgets clone() {
    return (AppsDynamiteSharedColumnsColumnWidgets) super.clone();
  }

}
