/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.cloudsearch.v1.model;

/**
 * An entity from the MDB namespace that is to be interpreted as a user. If using this for
 * authorization, you should only do an exact match on the peer role against user_name.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Search API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MdbUserProto extends com.google.api.client.json.GenericJson {

  /**
   * Do not set this field. Contact credentials-eng@ if you believe you absolutely need to use it.
   * This is the @prod.google.com Gaia ID that corresponds to the MDB user, see go/authn-merge for
   * details. This field may always be safely ignored when performing an authorization check.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gaiaId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userName;

  /**
   * Do not set this field. Contact credentials-eng@ if you believe you absolutely need to use it.
   * This is the @prod.google.com Gaia ID that corresponds to the MDB user, see go/authn-merge for
   * details. This field may always be safely ignored when performing an authorization check.
   * @return value or {@code null} for none
   */
  public java.lang.Long getGaiaId() {
    return gaiaId;
  }

  /**
   * Do not set this field. Contact credentials-eng@ if you believe you absolutely need to use it.
   * This is the @prod.google.com Gaia ID that corresponds to the MDB user, see go/authn-merge for
   * details. This field may always be safely ignored when performing an authorization check.
   * @param gaiaId gaiaId or {@code null} for none
   */
  public MdbUserProto setGaiaId(java.lang.Long gaiaId) {
    this.gaiaId = gaiaId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserName() {
    return userName;
  }

  /**
   * @param userName userName or {@code null} for none
   */
  public MdbUserProto setUserName(java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  @Override
  public MdbUserProto set(String fieldName, Object value) {
    return (MdbUserProto) super.set(fieldName, value);
  }

  @Override
  public MdbUserProto clone() {
    return (MdbUserProto) super.clone();
  }

}
