/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.contentwarehouse.v1.model;

/**
 * Please read go/people-api-howto:age on how to get age data. Message for the
 * `Person.age_range_repeated` field. Replaces the existing `Person.age_range` field.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Document AI Warehouse API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AppsPeopleOzExternalMergedpeopleapiAgeRangeType extends com.google.api.client.json.GenericJson {

  /**
   * Please read go/people-api-howto:age on how to get age data. Age of the user. The field is set
   * based on profile storage fields such as account birthday. If the source fields are not present,
   * `age_in_years` will be left unset.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer ageInYears;

  /**
   * Deprecated. Use go/supervised-accounts#capabilities-for-child-accounts instead. Denotes whether
   * the user is under the region based Age of Consent. The user's region is based on
   * ClientUserInfo.GlobalTos.AgreedLocation The age is inferred from Birthday field or
   * CertifiedBornBefore field. The region based AoC is specified at go/aoc.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ageOfConsentStatus;

  /**
   * Deprecated. Please read go/people-api-howto:age on how to get age data. Age range is populated
   * based on `account_birthday` and `certified_born_before`, which may not be set for dasher users.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ageRange;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AppsPeopleOzExternalMergedpeopleapiPersonFieldMetadata metadata;

  /**
   * Please read go/people-api-howto:age on how to get age data. Age of the user. The field is set
   * based on profile storage fields such as account birthday. If the source fields are not present,
   * `age_in_years` will be left unset.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAgeInYears() {
    return ageInYears;
  }

  /**
   * Please read go/people-api-howto:age on how to get age data. Age of the user. The field is set
   * based on profile storage fields such as account birthday. If the source fields are not present,
   * `age_in_years` will be left unset.
   * @param ageInYears ageInYears or {@code null} for none
   */
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType setAgeInYears(java.lang.Integer ageInYears) {
    this.ageInYears = ageInYears;
    return this;
  }

  /**
   * Deprecated. Use go/supervised-accounts#capabilities-for-child-accounts instead. Denotes whether
   * the user is under the region based Age of Consent. The user's region is based on
   * ClientUserInfo.GlobalTos.AgreedLocation The age is inferred from Birthday field or
   * CertifiedBornBefore field. The region based AoC is specified at go/aoc.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgeOfConsentStatus() {
    return ageOfConsentStatus;
  }

  /**
   * Deprecated. Use go/supervised-accounts#capabilities-for-child-accounts instead. Denotes whether
   * the user is under the region based Age of Consent. The user's region is based on
   * ClientUserInfo.GlobalTos.AgreedLocation The age is inferred from Birthday field or
   * CertifiedBornBefore field. The region based AoC is specified at go/aoc.
   * @param ageOfConsentStatus ageOfConsentStatus or {@code null} for none
   */
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType setAgeOfConsentStatus(java.lang.String ageOfConsentStatus) {
    this.ageOfConsentStatus = ageOfConsentStatus;
    return this;
  }

  /**
   * Deprecated. Please read go/people-api-howto:age on how to get age data. Age range is populated
   * based on `account_birthday` and `certified_born_before`, which may not be set for dasher users.
   * @return value or {@code null} for none
   */
  public java.lang.String getAgeRange() {
    return ageRange;
  }

  /**
   * Deprecated. Please read go/people-api-howto:age on how to get age data. Age range is populated
   * based on `account_birthday` and `certified_born_before`, which may not be set for dasher users.
   * @param ageRange ageRange or {@code null} for none
   */
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType setAgeRange(java.lang.String ageRange) {
    this.ageRange = ageRange;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public AppsPeopleOzExternalMergedpeopleapiPersonFieldMetadata getMetadata() {
    return metadata;
  }

  /**
   * @param metadata metadata or {@code null} for none
   */
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType setMetadata(AppsPeopleOzExternalMergedpeopleapiPersonFieldMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  @Override
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType set(String fieldName, Object value) {
    return (AppsPeopleOzExternalMergedpeopleapiAgeRangeType) super.set(fieldName, value);
  }

  @Override
  public AppsPeopleOzExternalMergedpeopleapiAgeRangeType clone() {
    return (AppsPeopleOzExternalMergedpeopleapiAgeRangeType) super.clone();
  }

}
