/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.contentwarehouse.v1.model;

/**
 * Proto descrbing an attachment to an Assistant Reminder. If the attachment has different behavior
 * on different surfaces (e.g., deeplinks), there will be multiple attachments attach to the
 * Reminder. Each of them will specify the surface type and the corresponding deeplink.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Document AI Warehouse API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AssistantRemindersAttachment extends com.google.api.client.json.GenericJson {

  /**
   * REQUIRED. An unique identifier for the attachment. We have a plan to index this field, so it's
   * marked as REQUIRED. Chat with opa-reminders-eng@ if you have a use case without an attachment
   * ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AssistantRemindersAttachmentLink link;

  /**
   * REQUIRED. Surface types this attachment should be shown.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> surfaceType;

  /**
   * REQUIRED. An unique identifier for the attachment. We have a plan to index this field, so it's
   * marked as REQUIRED. Chat with opa-reminders-eng@ if you have a use case without an attachment
   * ID.
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * REQUIRED. An unique identifier for the attachment. We have a plan to index this field, so it's
   * marked as REQUIRED. Chat with opa-reminders-eng@ if you have a use case without an attachment
   * ID.
   * @param id id or {@code null} for none
   */
  public AssistantRemindersAttachment setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public AssistantRemindersAttachmentLink getLink() {
    return link;
  }

  /**
   * @param link link or {@code null} for none
   */
  public AssistantRemindersAttachment setLink(AssistantRemindersAttachmentLink link) {
    this.link = link;
    return this;
  }

  /**
   * REQUIRED. Surface types this attachment should be shown.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getSurfaceType() {
    return surfaceType;
  }

  /**
   * REQUIRED. Surface types this attachment should be shown.
   * @param surfaceType surfaceType or {@code null} for none
   */
  public AssistantRemindersAttachment setSurfaceType(java.util.List<java.lang.String> surfaceType) {
    this.surfaceType = surfaceType;
    return this;
  }

  @Override
  public AssistantRemindersAttachment set(String fieldName, Object value) {
    return (AssistantRemindersAttachment) super.set(fieldName, value);
  }

  @Override
  public AssistantRemindersAttachment clone() {
    return (AssistantRemindersAttachment) super.clone();
  }

}
