/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.contentwarehouse.v1.model;

/**
 * This protocol buffer holds entrance-specific attributes for features of type TYPE_ENTRANCE.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Document AI Warehouse API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GeostoreEntranceProto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String allowance;

  /**
   * DEPRECATED. Please use enter_or_exit instead.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean canEnter;

  /**
   * Whether the target can be entered through this entrance. Whether the target can be exited
   * through this entrance.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean canExit;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAllowance() {
    return allowance;
  }

  /**
   * @param allowance allowance or {@code null} for none
   */
  public GeostoreEntranceProto setAllowance(java.lang.String allowance) {
    this.allowance = allowance;
    return this;
  }

  /**
   * DEPRECATED. Please use enter_or_exit instead.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanEnter() {
    return canEnter;
  }

  /**
   * DEPRECATED. Please use enter_or_exit instead.
   * @param canEnter canEnter or {@code null} for none
   */
  public GeostoreEntranceProto setCanEnter(java.lang.Boolean canEnter) {
    this.canEnter = canEnter;
    return this;
  }

  /**
   * Whether the target can be entered through this entrance. Whether the target can be exited
   * through this entrance.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getCanExit() {
    return canExit;
  }

  /**
   * Whether the target can be entered through this entrance. Whether the target can be exited
   * through this entrance.
   * @param canExit canExit or {@code null} for none
   */
  public GeostoreEntranceProto setCanExit(java.lang.Boolean canExit) {
    this.canExit = canExit;
    return this;
  }

  @Override
  public GeostoreEntranceProto set(String fieldName, Object value) {
    return (GeostoreEntranceProto) super.set(fieldName, value);
  }

  @Override
  public GeostoreEntranceProto clone() {
    return (GeostoreEntranceProto) super.clone();
  }

}
