/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.contentwarehouse.v1.model;

/**
 * Related entities.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Document AI Warehouse API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class NlpSaftEntityProfileRelated extends com.google.api.client.json.GenericJson {

  /**
   * Number of occurrences.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer count;

  /**
   * Inverse relations can be marked in a bidirectional graph.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean inverse;

  /**
   * Optional integer id for the relation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer relationId;

  /**
   * Optional external identifier for the relation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private NlpSaftIdentifier relationIdentifier;

  /**
   * Score for related entity, i.e. p(e->r | e).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float score;

  /**
   * Profile id of related entity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long targetId;

  /**
   * Optional external identifier for the target entity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private NlpSaftIdentifier targetIdentifier;

  /**
   * Name of related entity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String targetName;

  /**
   * Type of relation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * Number of occurrences.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCount() {
    return count;
  }

  /**
   * Number of occurrences.
   * @param count count or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setCount(java.lang.Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Inverse relations can be marked in a bidirectional graph.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getInverse() {
    return inverse;
  }

  /**
   * Inverse relations can be marked in a bidirectional graph.
   * @param inverse inverse or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setInverse(java.lang.Boolean inverse) {
    this.inverse = inverse;
    return this;
  }

  /**
   * Optional integer id for the relation.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getRelationId() {
    return relationId;
  }

  /**
   * Optional integer id for the relation.
   * @param relationId relationId or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setRelationId(java.lang.Integer relationId) {
    this.relationId = relationId;
    return this;
  }

  /**
   * Optional external identifier for the relation.
   * @return value or {@code null} for none
   */
  public NlpSaftIdentifier getRelationIdentifier() {
    return relationIdentifier;
  }

  /**
   * Optional external identifier for the relation.
   * @param relationIdentifier relationIdentifier or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setRelationIdentifier(NlpSaftIdentifier relationIdentifier) {
    this.relationIdentifier = relationIdentifier;
    return this;
  }

  /**
   * Score for related entity, i.e. p(e->r | e).
   * @return value or {@code null} for none
   */
  public java.lang.Float getScore() {
    return score;
  }

  /**
   * Score for related entity, i.e. p(e->r | e).
   * @param score score or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setScore(java.lang.Float score) {
    this.score = score;
    return this;
  }

  /**
   * Profile id of related entity.
   * @return value or {@code null} for none
   */
  public java.lang.Long getTargetId() {
    return targetId;
  }

  /**
   * Profile id of related entity.
   * @param targetId targetId or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setTargetId(java.lang.Long targetId) {
    this.targetId = targetId;
    return this;
  }

  /**
   * Optional external identifier for the target entity.
   * @return value or {@code null} for none
   */
  public NlpSaftIdentifier getTargetIdentifier() {
    return targetIdentifier;
  }

  /**
   * Optional external identifier for the target entity.
   * @param targetIdentifier targetIdentifier or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setTargetIdentifier(NlpSaftIdentifier targetIdentifier) {
    this.targetIdentifier = targetIdentifier;
    return this;
  }

  /**
   * Name of related entity.
   * @return value or {@code null} for none
   */
  public java.lang.String getTargetName() {
    return targetName;
  }

  /**
   * Name of related entity.
   * @param targetName targetName or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setTargetName(java.lang.String targetName) {
    this.targetName = targetName;
    return this;
  }

  /**
   * Type of relation.
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * Type of relation.
   * @param type type or {@code null} for none
   */
  public NlpSaftEntityProfileRelated setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public NlpSaftEntityProfileRelated set(String fieldName, Object value) {
    return (NlpSaftEntityProfileRelated) super.set(fieldName, value);
  }

  @Override
  public NlpSaftEntityProfileRelated clone() {
    return (NlpSaftEntityProfileRelated) super.clone();
  }

}
