/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.healthcare.v1alpha.model;

/**
 * Final response of importing resources. This structure will be included in the response to
 * describe the detailed outcome. It will only be included when the operation finishes.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Healthcare API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse extends com.google.api.client.json.GenericJson {

  /**
   * The number of resources that had errors.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long errorCount;

  /**
   * The total number of resources included in the source data. This is the sum of the success and
   * error counts.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long inputSize;

  /**
   * The FHIR store name the resources have been imported to, in the format `projects/{project_id}/l
   * ocations/{location_id}/datasets/{dataset_id}/fhirStores/{fhir_store_id}`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The number of resources that have been imported.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long successCount;

  /**
   * The number of resources that had errors.
   * @return value or {@code null} for none
   */
  public java.lang.Long getErrorCount() {
    return errorCount;
  }

  /**
   * The number of resources that had errors.
   * @param errorCount errorCount or {@code null} for none
   */
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse setErrorCount(java.lang.Long errorCount) {
    this.errorCount = errorCount;
    return this;
  }

  /**
   * The total number of resources included in the source data. This is the sum of the success and
   * error counts.
   * @return value or {@code null} for none
   */
  public java.lang.Long getInputSize() {
    return inputSize;
  }

  /**
   * The total number of resources included in the source data. This is the sum of the success and
   * error counts.
   * @param inputSize inputSize or {@code null} for none
   */
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse setInputSize(java.lang.Long inputSize) {
    this.inputSize = inputSize;
    return this;
  }

  /**
   * The FHIR store name the resources have been imported to, in the format `projects/{project_id}/l
   * ocations/{location_id}/datasets/{dataset_id}/fhirStores/{fhir_store_id}`.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The FHIR store name the resources have been imported to, in the format `projects/{project_id}/l
   * ocations/{location_id}/datasets/{dataset_id}/fhirStores/{fhir_store_id}`.
   * @param name name or {@code null} for none
   */
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * The number of resources that have been imported.
   * @return value or {@code null} for none
   */
  public java.lang.Long getSuccessCount() {
    return successCount;
  }

  /**
   * The number of resources that have been imported.
   * @param successCount successCount or {@code null} for none
   */
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse setSuccessCount(java.lang.Long successCount) {
    this.successCount = successCount;
    return this;
  }

  @Override
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse set(String fieldName, Object value) {
    return (GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse clone() {
    return (GoogleCloudHealthcareV1alphaFhirRestImportResourcesResponse) super.clone();
  }

}
