/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.vmmigration.v1alpha1.model;

/**
 * The details of an AWS instance disk.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the VM Migration API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AwsDiskDetails extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The ordinal number of the disk.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer diskNumber;

  /**
   * Output only. Size in GB.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long sizeGb;

  /**
   * Output only. AWS volume ID.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String volumeId;

  /**
   * Output only. The ordinal number of the disk.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getDiskNumber() {
    return diskNumber;
  }

  /**
   * Output only. The ordinal number of the disk.
   * @param diskNumber diskNumber or {@code null} for none
   */
  public AwsDiskDetails setDiskNumber(java.lang.Integer diskNumber) {
    this.diskNumber = diskNumber;
    return this;
  }

  /**
   * Output only. Size in GB.
   * @return value or {@code null} for none
   */
  public java.lang.Long getSizeGb() {
    return sizeGb;
  }

  /**
   * Output only. Size in GB.
   * @param sizeGb sizeGb or {@code null} for none
   */
  public AwsDiskDetails setSizeGb(java.lang.Long sizeGb) {
    this.sizeGb = sizeGb;
    return this;
  }

  /**
   * Output only. AWS volume ID.
   * @return value or {@code null} for none
   */
  public java.lang.String getVolumeId() {
    return volumeId;
  }

  /**
   * Output only. AWS volume ID.
   * @param volumeId volumeId or {@code null} for none
   */
  public AwsDiskDetails setVolumeId(java.lang.String volumeId) {
    this.volumeId = volumeId;
    return this;
  }

  @Override
  public AwsDiskDetails set(String fieldName, Object value) {
    return (AwsDiskDetails) super.set(fieldName, value);
  }

  @Override
  public AwsDiskDetails clone() {
    return (AwsDiskDetails) super.clone();
  }

}
