{
  "batchPath": "batch",
  "version_module": true,
  "protocol": "rest",
  "id": "cloudidentity:v1beta1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Identity API",
  "documentationLink": "https://cloud.google.com/identity/",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        }
      }
    }
  },
  "servicePath": "",
  "description": "API for provisioning and managing identity resources.",
  "canonicalName": "Cloud Identity",
  "basePath": "",
  "ownerDomain": "google.com",
  "version": "v1beta1",
  "ownerName": "Google",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "name": "cloudidentity",
  "resources": {
    "groups": {
      "methods": {
        "search": {
          "path": "v1beta1/groups:search",
          "flatPath": "v1beta1/groups:search",
          "description": "Searches for `Group`s matching a specified query.",
          "id": "cloudidentity.groups.search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "lookup": {
          "httpMethod": "GET",
          "path": "v1beta1/groups:lookup",
          "flatPath": "v1beta1/groups:lookup",
          "description": "Looks up the [resource\nname](https://cloud.google.com/apis/design/resource_names) of a `Group` by\nits `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.lookup"
        },
        "get": {
          "id": "cloudidentity.groups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Retrieves a `Group`.",
          "flatPath": "v1beta1/groups/{groupsId}",
          "httpMethod": "GET",
          "path": "v1beta1/{+name}"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "path": "v1beta1/{+name}",
          "flatPath": "v1beta1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "httpMethod": "DELETE"
        },
        "patch": {
          "flatPath": "v1beta1/groups/{groupsId}",
          "description": "Updates a `Group`.",
          "path": "v1beta1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.patch"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v1beta1/groups",
          "path": "v1beta1/groups",
          "id": "cloudidentity.groups.list",
          "description": "Lists the `Group`s under a customer or namespace.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "flatPath": "v1beta1/groups",
          "id": "cloudidentity.groups.create",
          "path": "v1beta1/groups",
          "httpMethod": "POST",
          "description": "Creates a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "modifyMembershipRoles": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+name}:modifyMembershipRoles",
              "httpMethod": "POST",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "description": "Lists the `Membership`s within a `Group`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta1/{+parent}/memberships",
              "httpMethod": "GET",
              "flatPath": "v1beta1/groups/{groupsId}/memberships"
            },
            "create": {
              "path": "v1beta1/{+parent}/memberships",
              "description": "Creates a `Membership`.",
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1beta1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1beta1/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}"
            },
            "lookup": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1beta1/{+parent}/memberships:lookup",
              "flatPath": "v1beta1/groups/{groupsId}/memberships:lookup",
              "description": "Looks up the [resource\nname](https://cloud.google.com/apis/design/resource_names) of a\n`Membership` by its `EntityKey`.",
              "httpMethod": "GET"
            },
            "get": {
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1beta1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Retrieves a `Membership`.",
              "httpMethod": "GET",
              "path": "v1beta1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "revision": "20200612"
}
