{
  "servicePath": "",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "resources": {
    "buyers": {
      "methods": {
        "getRemarketingTag": {
          "flatPath": "v1/buyers/{buyersId}:getRemarketingTag",
          "path": "v1/{+name}:getRemarketingTag",
          "id": "realtimebidding.buyers.getRemarketingTag",
          "description": "Gets remarketing tag for a buyer. A remarketing tag is a piece of\nJavaScript code that can be placed on a web page. When a user\nvisits a page containing a remarketing tag, Google adds the user to a user\nlist.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adexchange.buyer",
            "https://www.googleapis.com/auth/realtime-bidding"
          ]
        }
      },
      "resources": {
        "userLists": {
          "methods": {
            "update": {
              "id": "realtimebidding.buyers.userLists.update",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "httpMethod": "PUT",
              "flatPath": "v1/buyers/{buyersId}/userLists/{userListsId}",
              "path": "v1/{+name}",
              "description": "Update the given user list. Only user lists with URLRestrictions can be\nupdated."
            },
            "get": {
              "httpMethod": "GET",
              "id": "realtimebidding.buyers.userLists.get",
              "description": "Gets a user list by its name.",
              "flatPath": "v1/buyers/{buyersId}/userLists/{userListsId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ]
            },
            "list": {
              "flatPath": "v1/buyers/{buyersId}/userLists",
              "id": "realtimebidding.buyers.userLists.list",
              "path": "v1/{+parent}/userLists",
              "description": "Lists the user lists visible to the current user.",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "description": "Create a new user list.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "flatPath": "v1/buyers/{buyersId}/userLists",
              "id": "realtimebidding.buyers.userLists.create",
              "path": "v1/{+parent}/userLists"
            },
            "close": {
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "flatPath": "v1/buyers/{buyersId}/userLists/{userListsId}:close",
              "id": "realtimebidding.buyers.userLists.close",
              "httpMethod": "POST",
              "description": "Change the status of a user list to CLOSED. This prevents new users from\nbeing added to the user list.",
              "path": "v1/{+name}:close"
            },
            "open": {
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "httpMethod": "POST",
              "id": "realtimebidding.buyers.userLists.open",
              "flatPath": "v1/buyers/{buyersId}/userLists/{userListsId}:open",
              "path": "v1/{+name}:open",
              "description": "Change the status of a user list to OPEN. This allows new users to be added\nto the user list."
            },
            "getRemarketingTag": {
              "flatPath": "v1/buyers/{buyersId}/userLists/{userListsId}:getRemarketingTag",
              "id": "realtimebidding.buyers.userLists.getRemarketingTag",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "description": "Gets remarketing tag for a buyer. A remarketing tag is a piece of\nJavaScript code that can be placed on a web page. When a user\nvisits a page containing a remarketing tag, Google adds the user to a user\nlist.",
              "httpMethod": "GET",
              "path": "v1/{+name}:getRemarketingTag"
            }
          }
        },
        "creatives": {
          "methods": {
            "patch": {
              "id": "realtimebidding.buyers.creatives.patch",
              "path": "v1/{+name}",
              "flatPath": "v1/buyers/{buyersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "description": "Updates a creative."
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a creative.",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "path": "v1/{+parent}/creatives",
              "id": "realtimebidding.buyers.creatives.create",
              "flatPath": "v1/buyers/{buyersId}/creatives"
            },
            "list": {
              "flatPath": "v1/buyers/{buyersId}/creatives",
              "description": "Lists creatives.",
              "path": "v1/{+parent}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "id": "realtimebidding.buyers.creatives.list",
              "httpMethod": "GET"
            },
            "get": {
              "id": "realtimebidding.buyers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "path": "v1/{+name}",
              "flatPath": "v1/buyers/{buyersId}/creatives/{creativesId}",
              "description": "Gets a creative.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "bidders": {
      "resources": {
        "creatives": {
          "methods": {
            "watch": {
              "id": "realtimebidding.bidders.creatives.watch",
              "description": "Watches all creatives pertaining to a bidder. It is sufficient to invoke\nthis endpoint once per bidder. A Pub/Sub topic will be created and\nnotifications will be pushed to the topic when any of the bidder's\ncreatives change status. All of the bidder's service accounts will have\naccess to read from the topic.\nSubsequent invocations of this method will return the existing\nPub/Sub configuration.",
              "path": "v1/{+parent}/creatives:watch",
              "flatPath": "v1/bidders/{biddersId}/creatives:watch",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ]
            },
            "list": {
              "id": "realtimebidding.bidders.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/adexchange.buyer",
                "https://www.googleapis.com/auth/realtime-bidding"
              ],
              "flatPath": "v1/bidders/{biddersId}/creatives",
              "httpMethod": "GET",
              "path": "v1/{+parent}/creatives",
              "description": "Lists creatives."
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/authorized-buyers/apis/realtimebidding/reference/rest/",
  "id": "realtimebidding:v1",
  "mtlsRootUrl": "https://realtimebidding.mtls.googleapis.com/",
  "description": "Allows external bidders to manage their RTB integration with Google. This includes managing bidder endpoints, QPS quotas, configuring what ad inventory to receive via pretargeting, submitting creatives for verification, and accessing creative metadata such as approval status.",
  "batchPath": "batch",
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://realtimebidding.googleapis.com/",
  "name": "realtimebidding",
  "revision": "20200713",
  "rootUrl": "https://realtimebidding.googleapis.com/",
  "title": "Real-time Bidding API",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adexchange.buyer": {
          "description": "Manage your Ad Exchange buyer account configuration"
        },
        "https://www.googleapis.com/auth/realtime-bidding": {
          "description": "See, create, edit, and delete your Authorized Buyers and Open Bidding account entities"
        }
      }
    }
  },
  "canonicalName": "Real-time Bidding",
  "kind": "discovery#restDescription"
}
