{
  "rootUrl": "https://www.googleapis.com/",
  "discoveryVersion": "v1",
  "title": "Calendar API",
  "id": "calendar:v3",
  "ownerDomain": "google.com",
  "description": "Manipulates events and other calendar data.",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "revision": "20200610",
  "protocol": "rest",
  "batchPath": "batch/calendar/v3",
  "baseUrl": "https://www.googleapis.com/calendar/v3/",
  "resources": {
    "calendars": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "calendars/{calendarId}",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "description": "Updates metadata for a calendar. This method supports patch semantics.",
          "id": "calendar.calendars.patch"
        },
        "update": {
          "path": "calendars/{calendarId}",
          "id": "calendar.calendars.update",
          "description": "Updates metadata for a calendar.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a secondary calendar. Use calendars.clear for clearing all events on primary calendars.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "id": "calendar.calendars.delete",
          "path": "calendars/{calendarId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "calendars",
          "description": "Creates a secondary calendar.",
          "id": "calendar.calendars.insert",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ]
        },
        "clear": {
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "id": "calendar.calendars.clear",
          "description": "Clears a primary calendar. This operation deletes all events associated with the primary calendar of an account.",
          "path": "calendars/{calendarId}/clear",
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.calendars.get",
          "path": "calendars/{calendarId}",
          "description": "Returns metadata for a calendar."
        }
      }
    },
    "acl": {
      "methods": {
        "patch": {
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "id": "calendar.acl.patch",
          "description": "Updates an access control rule. This method supports patch semantics."
        },
        "watch": {
          "id": "calendar.acl.watch",
          "supportsSubscription": true,
          "description": "Watch for changes to ACL resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "httpMethod": "POST",
          "path": "calendars/{calendarId}/acl/watch"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.acl.get",
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "description": "Returns an access control rule."
        },
        "list": {
          "httpMethod": "GET",
          "id": "calendar.acl.list",
          "description": "Returns the rules in the access control list for the calendar.",
          "path": "calendars/{calendarId}/acl",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "supportsSubscription": true
        },
        "delete": {
          "id": "calendar.acl.delete",
          "description": "Deletes an access control rule.",
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "calendars/{calendarId}/acl/{ruleId}",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "description": "Updates an access control rule.",
          "httpMethod": "PUT",
          "id": "calendar.acl.update"
        },
        "insert": {
          "path": "calendars/{calendarId}/acl",
          "httpMethod": "POST",
          "id": "calendar.acl.insert",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "description": "Creates an access control rule."
        }
      }
    },
    "colors": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "colors",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.colors.get",
          "description": "Returns the color definitions for calendars and events."
        }
      }
    },
    "events": {
      "methods": {
        "quickAdd": {
          "id": "calendar.events.quickAdd",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ],
          "path": "calendars/{calendarId}/events/quickAdd",
          "description": "Creates an event based on a simple text string."
        },
        "list": {
          "path": "calendars/{calendarId}/events",
          "id": "calendar.events.list",
          "description": "Returns events on the specified calendar.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "httpMethod": "GET",
          "supportsSubscription": true
        },
        "patch": {
          "path": "calendars/{calendarId}/events/{eventId}",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ],
          "description": "Updates an event. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "calendar.events.patch"
        },
        "move": {
          "path": "calendars/{calendarId}/events/{eventId}/move",
          "id": "calendar.events.move",
          "description": "Moves an event to another calendar, i.e. changes an event's organizer.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ]
        },
        "instances": {
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.events.instances",
          "httpMethod": "GET",
          "path": "calendars/{calendarId}/events/{eventId}/instances",
          "description": "Returns instances of the specified recurring event."
        },
        "import": {
          "description": "Imports an event. This operation is used to add a private copy of an existing event to a calendar.",
          "path": "calendars/{calendarId}/events/import",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ],
          "httpMethod": "POST",
          "id": "calendar.events.import"
        },
        "get": {
          "path": "calendars/{calendarId}/events/{eventId}",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "httpMethod": "GET",
          "description": "Returns an event.",
          "id": "calendar.events.get"
        },
        "update": {
          "path": "calendars/{calendarId}/events/{eventId}",
          "httpMethod": "PUT",
          "description": "Updates an event.",
          "id": "calendar.events.update",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ]
        },
        "insert": {
          "id": "calendar.events.insert",
          "description": "Creates an event.",
          "path": "calendars/{calendarId}/events",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ],
          "httpMethod": "POST"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an event.",
          "path": "calendars/{calendarId}/events/{eventId}",
          "id": "calendar.events.delete",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events"
          ]
        },
        "watch": {
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "id": "calendar.events.watch",
          "description": "Watch for changes to Events resources.",
          "httpMethod": "POST",
          "path": "calendars/{calendarId}/events/watch"
        }
      }
    },
    "calendarList": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "path": "users/me/calendarList",
          "description": "Inserts an existing calendar into the user's calendar list.",
          "httpMethod": "POST",
          "id": "calendar.calendarList.insert"
        },
        "list": {
          "path": "users/me/calendarList",
          "id": "calendar.calendarList.list",
          "httpMethod": "GET",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "description": "Returns the calendars on the user's calendar list."
        },
        "get": {
          "description": "Returns a calendar from the user's calendar list.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "path": "users/me/calendarList/{calendarId}",
          "id": "calendar.calendarList.get"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "description": "Updates an existing calendar on the user's calendar list.",
          "path": "users/me/calendarList/{calendarId}",
          "id": "calendar.calendarList.update"
        },
        "patch": {
          "description": "Updates an existing calendar on the user's calendar list. This method supports patch semantics.",
          "path": "users/me/calendarList/{calendarId}",
          "id": "calendar.calendarList.patch",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "httpMethod": "PATCH"
        },
        "watch": {
          "id": "calendar.calendarList.watch",
          "httpMethod": "POST",
          "supportsSubscription": true,
          "description": "Watch for changes to CalendarList resources.",
          "path": "users/me/calendarList/watch",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Removes a calendar from the user's calendar list.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar"
          ],
          "path": "users/me/calendarList/{calendarId}",
          "id": "calendar.calendarList.delete"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.events.readonly",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "id": "calendar.channels.stop",
          "path": "channels/stop",
          "description": "Stop watching resources through this channel"
        }
      }
    },
    "settings": {
      "methods": {
        "list": {
          "path": "users/me/settings",
          "httpMethod": "GET",
          "id": "calendar.settings.list",
          "supportsSubscription": true,
          "description": "Returns all user settings for the authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ]
        },
        "get": {
          "path": "users/me/settings/{setting}",
          "description": "Returns a single user setting.",
          "id": "calendar.settings.get",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "httpMethod": "GET"
        },
        "watch": {
          "description": "Watch for changes to Settings resources.",
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/calendar.settings.readonly"
          ],
          "id": "calendar.settings.watch",
          "supportsSubscription": true,
          "httpMethod": "POST",
          "path": "users/me/settings/watch"
        }
      }
    },
    "freebusy": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/calendar",
            "https://www.googleapis.com/auth/calendar.readonly"
          ],
          "description": "Returns free/busy information for a set of calendars.",
          "httpMethod": "POST",
          "id": "calendar.freebusy.query",
          "path": "freeBusy"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/calendar.readonly": {
          "description": "View your calendars"
        },
        "https://www.googleapis.com/auth/calendar.settings.readonly": {
          "description": "View your Calendar settings"
        },
        "https://www.googleapis.com/auth/calendar.events.readonly": {
          "description": "View events on all your calendars"
        },
        "https://www.googleapis.com/auth/calendar": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/calendar.events": {
          "description": "View and edit events on all your calendars"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/google-apps/calendar/firstapp",
  "version": "v3",
  "servicePath": "calendar/v3/",
  "name": "calendar",
  "basePath": "/calendar/v3/"
}
