/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.datastream.v1.model;

/**
 * Time unit column partitioning. see https://cloud.google.com/bigquery/docs/partitioned-
 * tables#date_timestamp_partitioned_tables
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Datastream API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class TimeUnitPartition extends com.google.api.client.json.GenericJson {

  /**
   * Required. The partitioning column.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String column;

  /**
   * Optional. Partition granularity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String partitioningTimeGranularity;

  /**
   * Required. The partitioning column.
   * @return value or {@code null} for none
   */
  public java.lang.String getColumn() {
    return column;
  }

  /**
   * Required. The partitioning column.
   * @param column column or {@code null} for none
   */
  public TimeUnitPartition setColumn(java.lang.String column) {
    this.column = column;
    return this;
  }

  /**
   * Optional. Partition granularity.
   * @return value or {@code null} for none
   */
  public java.lang.String getPartitioningTimeGranularity() {
    return partitioningTimeGranularity;
  }

  /**
   * Optional. Partition granularity.
   * @param partitioningTimeGranularity partitioningTimeGranularity or {@code null} for none
   */
  public TimeUnitPartition setPartitioningTimeGranularity(java.lang.String partitioningTimeGranularity) {
    this.partitioningTimeGranularity = partitioningTimeGranularity;
    return this;
  }

  @Override
  public TimeUnitPartition set(String fieldName, Object value) {
    return (TimeUnitPartition) super.set(fieldName, value);
  }

  @Override
  public TimeUnitPartition clone() {
    return (TimeUnitPartition) super.clone();
  }

}
