on:
  workflow_dispatch:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]
  workflow_call:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]

name: generate
jobs:
  generate_one:
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        service: ${{fromJson(inputs.services)}}
    steps:
      - run: echo generating ${{ matrix.service }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: google-api-java-client-services
      - uses: actions/checkout@v2
        with:
          repository: googleapis/discovery-artifact-manager
          fetch-depth: 1
          path: discovery-artifact-manager
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8.18
      - run: |
          sudo apt update
          python3 --version
          pip install pip==21.3.1
          pip --version  
      - run: ./google-api-java-client-services/.github/workflows/generate.sh ${{ matrix.service }}
      - uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        token: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        commit-message: ${{ env.MESSAGE }}
        committer: ${{ env.AUTHOR }}
        author: ${{ env.AUTHOR }}
        branch: regenerate-${{ matrix.service }}
        title: ${{ env.MESSAGE }}
        body: 'Generated in GitHub action: https://github.com/${{ github.repository_owner }}/${{ github.repository }}/actions/workflows/codegen.yaml'
        add-paths: 'google-api-java-client-services/clients/google-api-services-${{ matrix.service }}'
        base: main
        push-to-fork: yoshi-code-bot/google-api-java-client-services

        env:
          - MESSAGE: 'chore: regenerate ${{ matrix.service }} client'
          - AUTHOR: Yoshi Code Bot <yoshi-automation@google.com>
