on:
  workflow_dispatch:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]
  workflow_call:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]

name: generate
jobs:
  generate_one:
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        service: ${{fromJson(inputs.services)}}
    steps:
      - run: echo generating ${{ matrix.service }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: google-api-java-client-services
      - uses: actions/checkout@v2
        with:
          repository: googleapis/discovery-artifact-manager
          fetch-depth: 1
          path: discovery-artifact-manager
      - run: |
          sudo apt update
          sudo apt install python3
          echo "using $(python3 --version)"
          curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
          python3 get-pip.py
      - run: ./google-api-java-client-services/.github/workflows/generate.sh ${{ matrix.service }}
      - uses: googleapis/code-suggester@v2 # takes the changes from git directory
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: ${{ github.repository_owner }}
          upstream_repo: google-api-java-client-services
          description: 'Generated in GitHub action: https://github.com/${{ github.repository_owner }}/${{ github.repository }}/actions/workflows/codegen.yaml'
          title: 'chore: regenerate ${{ matrix.service }} client'
          message: 'chore: regenerate ${{ matrix.service }} client'
          branch: regenerate-${{ matrix.service }}
          git_dir: 'google-api-java-client-services/clients/google-api-services-${{ matrix.service }}'
          primary: main
          force: true
          fork: true
