permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]
  workflow_call:
    inputs:
      services:
        required: true
        type: string
        description: A JSON array of service names. E.g., ["aiplatform"]

name: generate
jobs:
  generate_one:
    runs-on: 'ubuntu-24.04'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        service: ${{fromJson(inputs.services)}}
    steps:
      - run: echo generating ${MATRIX_SERVICE}
        env:
          MATRIX_SERVICE: ${{ matrix.service }}
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          fetch-depth: 1
          path: google-api-java-client-services
          token: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
          persist-credentials: false
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
        with:
          repository: googleapis/discovery-artifact-manager
          fetch-depth: 1
          path: discovery-artifact-manager
          token: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.8.18
      - run: |
          sudo apt update
          python3 --version
          pip install pip==21.3.1
          pip --version  
      - run: ./google-api-java-client-services/.github/workflows/generate.sh ${MATRIX_SERVICE}
        env:
          MATRIX_SERVICE: ${{ matrix.service }}
      - uses: googleapis/code-suggester@f9fef85aa02459e30e62526abe950341cbbd768b # v5
        env:
          ACCESS_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
        with:
          command: pr
          upstream_owner: ${{ github.repository_owner }}
          upstream_repo: google-api-java-client-services
          description: 'Generated in GitHub action: https://github.com/${{ github.repository_owner }}/${{ github.repository }}/actions/workflows/codegen.yaml'
          title: 'chore: regenerate ${{ matrix.service }} client'
          message: 'chore: regenerate ${{ matrix.service }} client'
          branch: regenerate-${{ matrix.service }}
          git_dir: 'google-api-java-client-services/clients/google-api-services-${{ matrix.service }}'
          primary: main
          force: true
          fork: true
