{
  "version": "v1",
  "canonicalName": "Cloud Identity",
  "name": "cloudidentity",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        }
      }
    }
  },
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "description": "API for provisioning and managing identity resources.",
  "id": "cloudidentity:v1",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "discoveryVersion": "v1",
  "revision": "20200927",
  "title": "Cloud Identity API",
  "resources": {
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "POST",
              "path": "v1/{+parent}/memberships"
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "httpMethod": "POST"
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "httpMethod": "GET",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "path": "v1/{+parent}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Deletes a `Membership`.",
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.delete"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.list",
              "description": "Lists the `Membership`s within a `Group`.",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Retrieves a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.get"
            }
          }
        }
      },
      "methods": {
        "get": {
          "path": "v1/{+name}",
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get"
        },
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:search",
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "description": "Searches for `Group`s matching a specified query.",
          "id": "cloudidentity.groups.search"
        },
        "create": {
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "description": "Creates a Group."
        },
        "delete": {
          "path": "v1/{+name}",
          "description": "Deletes a `Group`.",
          "httpMethod": "DELETE",
          "id": "cloudidentity.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}"
        },
        "patch": {
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "description": "Updates a `Group`."
        },
        "lookup": {
          "httpMethod": "GET",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "path": "v1/groups:lookup"
        },
        "list": {
          "path": "v1/groups",
          "id": "cloudidentity.groups.list",
          "description": "Lists the `Group`s under a customer or namespace.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/groups"
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "list": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "path": "v1/{+parent}/clientStates",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "httpMethod": "GET",
                  "description": "Lists the client states for the given search query."
                },
                "patch": {
                  "description": "Updates the client state for the device user",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "description": "Gets the client state for the device user",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get"
                }
              }
            }
          },
          "methods": {
            "cancelWipe": {
              "path": "v1/{+name}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "httpMethod": "POST",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe"
            },
            "approve": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "description": "Approves device to access user data.",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "httpMethod": "POST",
              "path": "v1/{+name}:approve"
            },
            "block": {
              "path": "v1/{+name}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "httpMethod": "POST",
              "description": "Blocks device from accessing user data",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "wipe": {
              "path": "v1/{+name}:wipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos."
            },
            "list": {
              "path": "v1/{+parent}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list",
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "httpMethod": "GET"
            },
            "lookup": {
              "path": "v1/{+parent}:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup"
            },
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}"
            }
          }
        }
      },
      "methods": {
        "create": {
          "httpMethod": "POST",
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created.",
          "id": "cloudidentity.devices.create"
        },
        "get": {
          "description": "Retrieves the specified device.",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.get"
        },
        "wipe": {
          "flatPath": "v1/devices/{devicesId}:wipe",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe",
          "description": "Wipes all data on the specified device.",
          "path": "v1/{+name}:wipe"
        },
        "cancelWipe": {
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "path": "v1/{+name}:cancelWipe"
        },
        "list": {
          "description": "Lists/Searches devices.",
          "path": "v1/devices",
          "httpMethod": "GET",
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.list"
        },
        "delete": {
          "description": "Deletes the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.delete",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        }
      }
    }
  },
  "version_module": true,
  "basePath": "",
  "documentationLink": "https://cloud.google.com/identity/",
  "ownerName": "Google",
  "rootUrl": "https://cloudidentity.googleapis.com/"
}
