{
  "servicePath": "",
  "id": "cloudidentity:v1",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        }
      }
    }
  },
  "canonicalName": "Cloud Identity",
  "resources": {
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Gets the client state for the device user",
                  "httpMethod": "GET",
                  "path": "v1/{+name}"
                },
                "patch": {
                  "description": "Updates the client state for the device user",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch"
                },
                "list": {
                  "path": "v1/{+parent}/clientStates",
                  "description": "Lists the client states for the given search query.",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "approve": {
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve",
              "description": "Approves device to access user data."
            },
            "list": {
              "id": "cloudidentity.devices.deviceUsers.list",
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "path": "v1/{+parent}/deviceUsers",
              "httpMethod": "GET",
              "description": "Lists/Searches DeviceUsers."
            },
            "cancelWipe": {
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "path": "v1/{+name}:cancelWipe",
              "httpMethod": "POST"
            },
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "description": "Retrieves the specified DeviceUser",
              "httpMethod": "GET"
            },
            "lookup": {
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "path": "v1/{+parent}:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup"
            },
            "wipe": {
              "path": "v1/{+name}:wipe",
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe"
            },
            "block": {
              "path": "v1/{+name}:block",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "description": "Blocks device from accessing user data"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data."
            }
          }
        }
      },
      "methods": {
        "list": {
          "path": "v1/devices",
          "id": "cloudidentity.devices.list",
          "httpMethod": "GET",
          "flatPath": "v1/devices",
          "description": "Lists/Searches devices."
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "description": "Deletes the specified device."
        },
        "get": {
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "description": "Retrieves the specified device.",
          "id": "cloudidentity.devices.get",
          "flatPath": "v1/devices/{devicesId}"
        },
        "create": {
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created.",
          "id": "cloudidentity.devices.create",
          "httpMethod": "POST"
        },
        "wipe": {
          "id": "cloudidentity.devices.wipe",
          "path": "v1/{+name}:wipe",
          "description": "Wipes all data on the specified device.",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "httpMethod": "POST"
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST"
        }
      }
    },
    "groups": {
      "methods": {
        "create": {
          "description": "Creates a Group.",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "id": "cloudidentity.groups.create",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST"
        },
        "search": {
          "id": "cloudidentity.groups.search",
          "path": "v1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Searches for Groups.",
          "httpMethod": "GET",
          "flatPath": "v1/groups:search"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}",
          "description": "Retrieves a Group.",
          "id": "cloudidentity.groups.get",
          "path": "v1/{+name}"
        },
        "list": {
          "flatPath": "v1/groups",
          "httpMethod": "GET",
          "id": "cloudidentity.groups.list",
          "path": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists groups within a customer or a domain."
        },
        "lookup": {
          "description": "Looks up [resource name](https://cloud.google.com/apis/design/resource_names) of a Group by its EntityKey.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.lookup",
          "httpMethod": "GET",
          "flatPath": "v1/groups:lookup",
          "path": "v1/groups:lookup"
        },
        "delete": {
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "description": "Deletes a Group."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.patch",
          "description": "Updates a Group.",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.create",
              "description": "Creates a Membership.",
              "path": "v1/{+parent}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "path": "v1/{+name}",
              "description": "Retrieves a Membership."
            },
            "list": {
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships",
              "httpMethod": "GET",
              "description": "Lists Memberships within a Group.",
              "id": "cloudidentity.groups.memberships.list"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a Membership.",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:lookup",
              "description": "Looks up [resource name](https://cloud.google.com/apis/design/resource_names) of a Membership within a Group by member's EntityKey.",
              "id": "cloudidentity.groups.memberships.lookup",
              "httpMethod": "GET"
            }
          }
        }
      }
    }
  },
  "basePath": "",
  "revision": "20200912",
  "batchPath": "batch",
  "title": "Cloud Identity API",
  "documentationLink": "https://cloud.google.com/identity/",
  "ownerName": "Google",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "ownerDomain": "google.com",
  "description": "API for provisioning and managing identity resources.",
  "protocol": "rest",
  "name": "cloudidentity",
  "version": "v1",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://cloudidentity.googleapis.com/"
}
