{
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "basePath": "",
  "id": "cloudidentity:v1",
  "canonicalName": "Cloud Identity",
  "documentationLink": "https://cloud.google.com/identity/",
  "description": "API for provisioning and managing identity resources.",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        }
      }
    }
  },
  "version_module": true,
  "title": "Cloud Identity API",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "resources": {
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships",
              "httpMethod": "POST"
            },
            "modifyMembershipRoles": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "path": "v1/{+name}:modifyMembershipRoles"
            },
            "get": {
              "path": "v1/{+name}",
              "description": "Retrieves a `Membership`.",
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:lookup",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "id": "cloudidentity.groups.memberships.lookup"
            },
            "delete": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`.",
              "path": "v1/{+name}"
            },
            "list": {
              "path": "v1/{+parent}/memberships",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.list",
              "description": "Lists the `Membership`s within a `Group`."
            }
          }
        }
      },
      "methods": {
        "search": {
          "id": "cloudidentity.groups.search",
          "description": "Searches for `Group`s matching a specified query.",
          "flatPath": "v1/groups:search",
          "path": "v1/groups:search",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists the `Group`s under a customer or namespace.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "id": "cloudidentity.groups.list"
        },
        "lookup": {
          "httpMethod": "GET",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "flatPath": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:lookup"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "description": "Creates a Group.",
          "id": "cloudidentity.groups.create"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`.",
          "httpMethod": "DELETE",
          "id": "cloudidentity.groups.delete",
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}"
        },
        "patch": {
          "path": "v1/{+name}",
          "description": "Updates a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Retrieves a `Group`.",
          "id": "cloudidentity.groups.get",
          "flatPath": "v1/groups/{groupsId}"
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "resources": {
            "clientStates": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "path": "v1/{+name}",
                  "description": "Updates the client state for the device user",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch"
                },
                "get": {
                  "description": "Gets the client state for the device user",
                  "path": "v1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "description": "Lists the client states for the given search query.",
                  "path": "v1/{+parent}/clientStates"
                }
              }
            }
          },
          "methods": {
            "cancelWipe": {
              "path": "v1/{+name}:cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list",
              "description": "Lists/Searches DeviceUsers.",
              "httpMethod": "GET",
              "path": "v1/{+parent}/deviceUsers"
            },
            "wipe": {
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST",
              "path": "v1/{+name}:wipe"
            },
            "get": {
              "path": "v1/{+name}",
              "description": "Retrieves the specified DeviceUser",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "id": "cloudidentity.devices.deviceUsers.get",
              "httpMethod": "GET"
            },
            "lookup": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "path": "v1/{+parent}:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "httpMethod": "GET",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]"
            },
            "block": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "description": "Blocks device from accessing user data",
              "path": "v1/{+name}:block",
              "httpMethod": "POST"
            },
            "delete": {
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data."
            },
            "approve": {
              "description": "Approves device to access user data.",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "httpMethod": "POST"
            }
          }
        }
      },
      "methods": {
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe"
        },
        "wipe": {
          "flatPath": "v1/devices/{devicesId}:wipe",
          "description": "Wipes all data on the specified device.",
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe"
        },
        "create": {
          "description": "Creates a device. Only company-owned device may be created.",
          "id": "cloudidentity.devices.create",
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "description": "Deletes the specified device.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "flatPath": "v1/devices/{devicesId}"
        },
        "list": {
          "flatPath": "v1/devices",
          "httpMethod": "GET",
          "description": "Lists/Searches devices.",
          "path": "v1/devices",
          "id": "cloudidentity.devices.list"
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Retrieves the specified device."
        }
      }
    }
  },
  "ownerName": "Google",
  "name": "cloudidentity",
  "ownerDomain": "google.com",
  "revision": "20201110",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "servicePath": ""
}
