/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.binaryauthorization.v1.model;

/**
 * A bundle of Sigstore public keys, used to verify Sigstore signatures. A signature is
 * authenticated by a `SigstorePublicKeySet` if any of the keys verify it.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Binary Authorization API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SigstorePublicKeySet extends com.google.api.client.json.GenericJson {

  /**
   * Required. `public_keys` must have at least one entry.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<SigstorePublicKey> publicKeys;

  static {
    // hack to force ProGuard to consider SigstorePublicKey used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(SigstorePublicKey.class);
  }

  /**
   * Required. `public_keys` must have at least one entry.
   * @return value or {@code null} for none
   */
  public java.util.List<SigstorePublicKey> getPublicKeys() {
    return publicKeys;
  }

  /**
   * Required. `public_keys` must have at least one entry.
   * @param publicKeys publicKeys or {@code null} for none
   */
  public SigstorePublicKeySet setPublicKeys(java.util.List<SigstorePublicKey> publicKeys) {
    this.publicKeys = publicKeys;
    return this;
  }

  @Override
  public SigstorePublicKeySet set(String fieldName, Object value) {
    return (SigstorePublicKeySet) super.set(fieldName, value);
  }

  @Override
  public SigstorePublicKeySet clone() {
    return (SigstorePublicKeySet) super.clone();
  }

}
